### PR TITLE
Added a search bar

### LINKED ISSUE #174: [Feature] Add Search Bar for searching components
### What would you like to share?

@Rakesh9100  we can add a search bar on the front page of beatify where people can search their css element by their own choice . i haven't done work on this feature before but i can try ? should we do this?

### Additional information

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pranjal12-web**
# Fixes Issue🛠️

Closes #174 

# Description👨‍💻 
Added a search bar to search compnents.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
tested locally on my machine.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-21 022255

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your search bar to the top of the components section page and not in the home page @pranjal12-web

**Comment by Rakesh9100** [comment]
Not done, you have to place this search bar at the top in the components section. When we click on `Get Components` button, then components section comes but search bar should come and below that the componentss!! @pranjal12-web

**Comment by pranjal12-web** [comment]
https://github.com/Rakesh9100/Beautiify/assets/67697534/6acf8419-fa8e-4885-9c13-c4ebff4ce7d5

**Comment by pranjal12-web** [comment]
@Rakesh9100 kindly check once as  when i am testing locally , i can see those required changes

**Comment by Rakesh9100** [comment]
> Beautiify.-.Google.Chrome.2024-01-22.18-53-59.mp4

As you can see, search bar is coming in the home page which we don't want. It should come on the second page only when clicked on `Get Components` @pranjal12-web

**Pull request closed without merging**
