### PR TITLE
Enhanced the home page with gradients

### LINKED ISSUE #896: [Style] Enhance the home page with gradients
### What's the style idea?

We need to improve the aesthetic appeal of the site. Currently, the boxes have a standard background and text style. I want to add a gradient background , to add a touch of elegance ,  and complementary text for the component boxes. 
enhanced_image
Removing shadow from text will make it more legible.

please assign me this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by nainika0305**
# Fixes Issue🛠️

Closes #896 

# Description👨‍💻

I have implemented some design enhancements to improve the visual appeal of the website. Specifically, I added gradient backgrounds to the component boxes, updated the colors and shadows, and modified the background and appearance of the search bar button. These changes have been made for both light and dark modes.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### Light mode :
image

### Light mode with hover :
image

### Dark mode :
image

### Dark mode with hover :
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When we hover over any box, the page or box tends to shift down or page tend to shift down. Pls make it still and smooth transition @nainika0305

**Comment by nainika0305** [comment]
ok will fix that

**Comment by Rakesh9100** [comment]
Make the new commits in this same PR, don't close this @nainika0305

**Comment by nainika0305** [comment]
Hi @Rakesh9100 i have made a commit.

**Comment by nainika0305** [comment]
@Rakesh9100 By mistake i made another issues commit into this pull request , but now i have reverted the commit. Please check

**Comment by nainika0305** [comment]
Hi @Rakesh9100  
i have completed my work .. can you please check ?
Let me know if you would like any changes to be done

**Pull request merged**
