### PR TITLE
Added new component category : Footers

### LINKED ISSUE #207: [Feature] : New component For footers
### Description

We can create **new section** of **components** for different types of **footers**.

Every Website has a footer in which the give their **social media acounts** , information of website and  other information.

This feature will help users to create their footers and the will get different ideas as new footers will be added to it in future.

I will add a footer of website  i had already made  in that component  its **screenshot is attached**.

While creating it i will follow the structure of files/folders created for website i will not disturbe it.

Kindly assign this issue to me under IWOC2024.

### Screenshots

Screenshot 2024-01-14 222732

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️

Issue #207 New component for footers.

Closes #207

# Description👨‍💻 

**Added a new section** of components for different types of footers.
And also added a **Animated Waves footer** in it.

While creating this I had taken care of the **original structure of Website**.

I had also provided the required links in it.

# How this has been tested✅

This is tested by me by running the website. All is Working Well.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots📷
Screenshot 2024-01-15 154121
Screenshot 2024-01-15 154142
Screenshot 2024-01-15 154010

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly check

**Comment by Rakesh9100** [comment]
> May I get **hard label** for this work😊

You don't have to ask for it. I will definitely provide the label depending on the work as hard work and dedication should not go in vain @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Ok sir I will do all these changes @Rakesh9100

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly check now.

**Comment by Rakesh9100** [comment]
Good job, Merged!! ✨🎉 @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
Thankyou sir 😊

**Pull request merged**
