### PR TITLE
Added Scroll Triggered Navigation Bar

### LINKED ISSUE #203: [Feature] Scroll Triggered Navigation Bar
### Description

Similar to fixed, but becomes visible only after the user scrolls down a certain distance.

Maximizes screen real estate when not in use.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/9b28d739-8055-454d-8ba3-ad4845dafa9f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #203 

# Description👨‍💻 

Added sticky navbar , when we scroll down nav goes out of webpage and vice versa
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/142514166/6cfaefa2-1898-44db-9839-1b78995904a3

### CODE REVIEW

**Comment by AbhineshJha** [comment]
done sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Rename your folder to `Scroll-Triggered-Navigation-Bar` or `Partial-Sticky-Navigation-Bar` whichever you feel good since it is not complete sticky navbar @AbhineshJha

**Comment by AbhineshJha** [comment]
have a look @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged!! ✨ @AbhineshJha

**Pull request merged**
