### PR TITLE
Added more footer components

### LINKED ISSUE #824: [Feature] Add more footer components
### Description

1. Parallax Footer
2. Split Footer
3. Interactive Footer
4.  Sticky Footer
Adding these footers

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
# Fixes Issue🛠️

Closes #824 

# Description👨‍💻

I have added 
1. Parallax Footer
2. Split Footer
3. Interactive Footer
4. Sticky Footer
and I have added these footers to footers page in asset.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project

# Screenshots/GIF📷

## 1. Interactive Footer
Screenshot 2024-06-20 225548
Screenshot 2024-06-20 225613

## 2. Parallax Footer
Screenshot 2024-06-20 225644
Screenshot 2024-06-20 225653

## 3. Split Footer
Screenshot 2024-06-20 225817

## 4. Sticky Footer
Screenshot 2024-06-20 225851

@Rakesh9100 Please label this PR under level3 in GSSoC

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls separate CSS files in `style.css` file and JS to `script.js` wherever required and make the new commits in this same PR @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 added separate css files and js files

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Please merge this PR under GSSoC.. Its been long time since I created this PR

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100  I have made corrections long time ago

**Pull request merged**
