### PR TITLE
Added Animated Form

### LINKED ISSUE #93: Animated Login Form
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add an animated Login form.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by rishicds**
# Fixes Issue🛠️

Closes #93 

# Description👨‍💻 

Added an Animated Login Form

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Hey @rishicds This PR also includes your Liquid Button commits. Pls fix it.

**Comment by Rakesh9100** [comment]
Instead of closing this and creating a new PR, you can just delete those files and push make the commit @rishicds

**Comment by rishicds** [comment]
Oh, I'll I didn't know about that , should I reopen that issue now or will this one be merged? @Rakesh9100

**Comment by Rakesh9100** [comment]
As now you have already created new PR, so will merge that.

But try to fix errors in the first PR only if you opened that from the next time. If commits error or any other errors are major and not getting fixed, then only close and create a new PR @rishicds

**Comment by rishicds** [comment]
Okay, thank you :). I'll keep it in mind from next time.

**Pull request closed without merging**
