### PR TITLE
Fixed the contact form responsiveness

### LINKED ISSUE #1406: [Bug] Fix the contact form responsiveness
### Description

🐞 Bug Report: Text Area Scrollbar on smaller screens

Issue:-
The text area on the form is currently displaying a scrollbar on smaller screens, which makes it look cluttered and affects the user experience. Users may find it difficult to view and edit their message due to limited space within the text area.

Fix:-
Increase the height of the text area to ensure that users can view and edit their entire message without needing to scroll. Additionally, apply appropriate padding within the text area to improve spacing and make the input feel more spacious and user-friendly.

@Rakesh9100 Sir please assign this issue to me ...

### Screenshots

bug

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sammy0318**
# Fixes Issue🛠️

Closes #1406 

# Description👨‍💻

Fixed the text area scrollbar problem on the contact page and made contact page fully responsive.

# Type of Change📄

- [x] Bug fix (non-breaking change which fixes a bug)
- [x] Style (non-breaking change which improves website style or formatting)
- [x] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### Before :-
395848894-dc7415da-336d-4a8c-a8e1-5a6baa1be482

### After :- 
395849025-0a1a1d67-1cb0-4afa-8988-eadd05a2f157

Thank you so much @Rakesh9100 ..

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Please mention the issue number related to this PR, fill the PR template properly from the next time @sammy0318

**Comment by sammy0318** [comment]
> Please mention the issue number related to this PR, fill the PR template properly from the next time @sammy0318

#1406 issue resolved 

Issue:-
The text area on the form is currently displaying a scrollbar , which makes it look cluttered and affects the user experience. Users may find it difficult to view and edit their message due to limited space within the text area.

Fix:-
Increase the height of the text area to ensure that users can view and edit their entire message without needing to scroll. Additionally, apply appropriate padding within the text area to improve spacing and make the input feel more spacious and user-friendly.

**Comment by Rakesh9100** [comment]
Can I know why you have closed the similar PR for this issue, I see both are same @sammy0318

**Comment by Rakesh9100** [comment]
Avoid repeatedly opening and closing PRs. Instead, focus on fixing the issue within the first PR itself to maintain good open-source practices @sammy0318

**Comment by sammy0318** [comment]
> Avoid repeatedly opening and closing PRs. Instead, focus on fixing the issue within the first PR itself to maintain good open-source practices @sammy0318 

Okay sir 👍

**Pull request merged**
