### PR TITLE
Gradient Tooltip Added

### LINKED ISSUE #1248: [Feature] Add Gradient Tooltip and Mario Themed Tooltip
### Description

Two new tooltip components in the library
1. Gradient Tooltip
2. Mario themed tooltip

### Screenshots

Screen Shot 2024-07-15 at 5 06 09 PM
Screen Shot 2024-07-15 at 5 07 12 PM

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by hars-21**
# Fixes Issue🛠️

Closes #1248 

# Description👨‍💻

Added a new tooltip in the library - The gradient Tooltip

# Type of Change📄

- [ ] Bug fix (non-breaking change which fixes a bug)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Style (non-breaking change which improves website style or formatting)
- [ ] Documentation (non-breaking change which updates or adds documentation)
- [ ] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screen Shot 2024-08-01 at 10 16 16 PM
Screen Shot 2024-08-01 at 10 16 27 PM

### CODE REVIEW

**Comment by hars-21** [comment]
@Rakesh9100 Please review my PR

**Comment by Rakesh9100** [comment]
Pls don't make any unnecessary indentation changes in tooltips.html file, just add your component part and no other changes @hars-21

**Comment by hars-21** [comment]
Hey @Rakesh9100 I have made the changes you asked. Added mario tooltip and fixed the indentation. Please review.

**Comment by hars-21** [comment]
@Rakesh9100 please review the new changes. Thanks!

**Comment by Rakesh9100** [comment]
Keep all your file indentation as 4 spaces and not 8 tabs and make the new commits @hars-21 

And always do the same for your every PR!

**Comment by hars-21** [comment]
Ok , will make the changes

**Comment by hars-21** [comment]
@Rakesh9100 Done!

**Review by hars-21 — COMMENTED** [review]
I have made the changes, IDK why in github it is showing like this but i have removed the previous indentation.

**Comment by hars-21** [comment]
@Rakesh9100 Please merge this PR. If you find indentation error after merging, you can revert it back. I have fixed.

**Pull request closed without merging**
