### PR TITLE
Added Black Red Signup Form

### LINKED ISSUE #804: [Feature] Add Black Red Signup Form
### Description

**Elegant and pleasing black and red design** 

(GSSOC contribution)

### Screenshots

Screenshot 2024-05-25 143443

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Vaishnavi1047**
# Fixes Issue🛠️

Closes #804 

# Description👨‍💻 

Added a new black red sign up form.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-05-25 143443

### CODE REVIEW

**Comment by Vaishnavi1047** [comment]
ISSUE NO #804

**Comment by Rakesh9100** [comment]
Why `Pink Card` folder is present since this issue is only to add `Black Red Signup Form`, and also add your form in `forms.html` file under assets/html_files to display on the website @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
Two issues were there one pink card was also assigned. Okay sir will do
that as soon as possible for that form

**Comment by Rakesh9100** [comment]
Solve only one issue through this PR by keeping files of only one form in this, and create another PR for another issue @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
I do have created another pr don't know why it didn't get form

**Comment by Vaishnavi1047** [comment]
done with the commits

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged to the repo under GSSOC 2k24 🥳🎉 @Vaishnavi1047

**Pull request merged**
