### PR TITLE
Added Neuromorphism background

### LINKED ISSUE #2: Neuromorphism Background
Add a neuromorphism background inside Backgrounds components.

### PR DESCRIPTION
**Pull request by itsmeabhishek03**
# Fixes Issue🛠️

Closes #2 

# Description👨‍💻 

Added Neuromorphism background

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

just click on live server to test it because it includes html and css

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Why second PR is opened? @itsmeabhishek03 

And properly work on the suggesed changes as mentioned on the first PR in the last comment.

**Comment by itsmeabhishek03** [comment]
> Why second PR is opened? @itsmeabhishek03
> 
> And properly work on the suggesed changes as mentioned on the first PR in the last comment.

sorry i made this PR before your comment, I messed up some branches can you please close all my PR's and i will make a new PR with all specified changes please !!

**Comment by Rakesh9100** [comment]
Closed the previous PR.

Can you make all your changes to this PR only insteadof again creating a new one @itsmeabhishek03

**Comment by itsmeabhishek03** [comment]
> Closed the previous PR.
> 
> Can you make all your changes to this PR only instead of again creating a new one @itsmeabhishek03

ok

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉 @itsmeabhishek03

**Pull request merged**
