### PR TITLE
Added 3d Breadcrumb

### LINKED ISSUE #143: Addition of 3D Breadcrumb
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i would like to add a new 3d breadcrumb.
please assign it to me under swoc'24

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #143

# Description👨‍💻 
Add 3d breadcrumb

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
bread

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100  can u plz check?

**Comment by Rakesh9100** [comment]
image

Pls align everything to center of the screen @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 can u plz check whether its alright now or not?

**Comment by Rakesh9100** [comment]
Merged!! ✨ @GhoshAditi

**Comment by rishicds** [comment]
Nice addition! @GhoshAditi

**Pull request merged**
