### PR TITLE
Created and linked seperate contributors page

### LINKED ISSUE #117: [Feat]: Create a separate contributors page
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to create a separate contributors page and remove the already existing contributors section from the main page.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by sksinha2410**
# Fixes Issue🛠️

Closes #117 

# Description👨‍💻 

Created contibutor html, css and js file in their respective folder and linked all.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor
- 
Screenshot 2024-01-15 at 3 44 48 PM

### CODE REVIEW

**Comment by sksinha2410** [comment]
If any additional info required then kindly let me know

**Comment by Rakesh9100** [comment]
Pls change the background of this to the background of the contact page and reduce the height and width of contributor-card @sksinha2410

**Comment by sksinha2410** [comment]
completed as per instruction (changed background and size)

**Comment by Rakesh9100** [comment]
Don't change the background of the home page!!

image
No space should be there below the footer @sksinha2410

**Comment by sksinha2410** [comment]
fixed

that was overlapping with 
    <link rel="stylesheet" type="text/css" href="./assets/css_files/contributor.css"> in index.html

**Comment by sksinha2410** [comment]
Fixed as per instructions

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @sksinha2410

**Pull request merged**
