### PR TITLE
Added Glitch Effect Button

### LINKED ISSUE #1106: [Feature] Add Glitch Effect Button
### Description

On hover of the button we get glitch Effect For the button

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Fixes Issue🛠️

Closes #1106 

# Description👨‍💻

I Have Added A Glitch Effect Button On hover we will see a glitch Effect.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Please Review the PR Soon

**Comment by Rakesh9100** [comment]
Pls mention about your work done in the Description section above @Saipradyumnagoud

**Comment by Rakesh9100** [comment]
Pls mention your work done in the Description section above, also attach the screenshot @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Yes i  have Added Description and Screenshot

**Pull request merged**
