### PR TITLE
Added Skeuomorphism Button

### LINKED ISSUE #579: [Feature] Adding Skeuomorphism Button
### Description

Will add a new "Skeuomorphism Button" in Button section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/101503723/a76e81a3-eddc-426a-b6b4-41e1e469d310

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Shubh484**
# Fixes Issue🛠️

Closes #579 

# Description👨‍💻 

Added the Skeuomorphism button in the button section.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-02-16 225104

### CODE REVIEW

**Comment by Shubh484** [comment]
Please check and merge my PR.

**Comment by Rakesh9100** [comment]
Mention the issue number this PR closes @Shubh484

**Comment by Rakesh9100** [comment]
Mention the issue number this PR closes @Shubh484

**Comment by Shubh484** [comment]
Issue number is - 579

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Shubh484

**Pull request merged**
