### PR TITLE
added a new gaming breadcrumb.

### LINKED ISSUE #280: [Feature] Add a new breadcrumb
### Description

It is very good breadcrumb and has spherical corners with voilet effect in it.It looks sassy and modern too.

### Screenshots
[Screencast from 17-01-24 05:49:06 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/156535575/a8e79b29-662c-45db-bd02-0d497d0487d6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivam101203**
# Fixes Issue🛠️ #280

closes #280

# Description👨‍💻 
Added a new breadcrumb which are used for gaming as it looks sassy and modern .

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
[Screencast from 17-01-24 05:49:06 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/156535575/04783f56-a5b6-4925-8aa3-e6bb383ac233)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @shivam101203

**Comment by shivam101203** [comment]
Okksir

**Comment by Rakesh9100** [comment]
Why have you closed this PR as well as PR #311 
Don't spam PRs by opening and closing again and again else you will not be assigned to any issues.

Learn to resolve changes, errors and conflicts in the same PR without closing it first!! @shivam101203

**Comment by shivam101203** [comment]
Okk sorry sir

**Pull request closed without merging**
