### PR TITLE
Added Text To Voice Form & QR Code Generator Form

### LINKED ISSUE #584: [Feature] Add Text To Voice Form & QR Code Generator Form
### What would you like to share?

Want to add these forms:
1. Text To Voice Converter form - Contains a text area to write texts and later converts it into voice.
2. QR Code generator form - Just enter any URL of a website and get a qr code.
3. Modal/ Popup login form - Create a form that pops up in a modal window when a button is clicked.

### Additional information

Please assign me under JWOC 2024

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ratnojitsaha**
# Fixes Issue🛠️

Closes #584 

# Description👨‍💻 

Text To Voice Form - Contains a text area to write texts and later converts it into voice .
QR Code Generator Form - Any text or link to QR code generator with customizable sizes and download option.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

On my local system.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (549)

Screenshot (552)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add your forms in `forms.html` file as well @ratnojitsaha

**Comment by ratnojitsaha** [comment]
YES 1 SEC

**Comment by ratnojitsaha** [comment]
@Rakesh9100 added

**Comment by ratnojitsaha** [comment]
@Rakesh9100 please check i have changed it

**Comment by Rakesh9100** [comment]
Merged 🎉 @ratnojitsaha

**Comment by Rakesh9100** [comment]
No problem @ratnojitsaha

**Pull request merged**
