### PR TITLE
Fixed hamburger menu in component category pages

### LINKED ISSUE #592: [Bug] Hamburger menu not working in component category pages
Fix the hamburger menu not coming up in every component category pages.

### PR DESCRIPTION
**Pull request by pb0126**
# Fixes Issue🛠️

Closes #592 

# Description👨‍💻 
The hamburger menu was not working on the component category page, after adding js files to the page it was working fine.
# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

The changes has been through tested by visiting one by one and using Chrome Developer tools

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Why the space is uneven between Contributors and Contact @pb0126

**Comment by Rakesh9100** [comment]
image

Why the space is uneven between Contributors and Contact, pls fix @pb0126

**Comment by Rakesh9100** [comment]
image

### Why the space is uneven between Contributors and Contact, pls fix @pb0126

**Comment by pb0126** [comment]
Okay Fixing

**Pull request closed without merging**
