### PR TITLE
Added custom cursor to the website

### LINKED ISSUE #864: [Feature] Add custom cursor to the website
### Description

Addition of Custom Cursor.
Which gives enhancement to the cursor pointer.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Fixes Issue🛠️

Closes #864 

# Description👨‍💻

Addition of Custom Cursor, which gives enhancement to the cursor pointer.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/154777864/be375570-267b-4e3b-8dd7-1142b90a977b

https://github.com/Rakesh9100/Beautiify/assets/154777864/21d645a9-e642-4746-96fb-33e717d91775

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please view the output in the above screen recording

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please view the output in the above screen recording

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR and add level label

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please add GSSOC label and level and merge the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR.

**Comment by Rakesh9100** [comment]
Pls implement the same cursor in About, Contributors, Contact and all the components Category pages such as Accordions, Backgrounds, etc @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR , the feature is added to all the webpages.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please review the PR

**Pull request merged**
