### PR TITLE
Added an about us section

### LINKED ISSUE #89: [Feature] Add an about us section
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

to add a about us page for providing better info about the website and its uses

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by praptisharma28**
# Fixes Issue🛠️

Closes #89 

# Description👨‍💻 

Added an about page.

# Type of change📄
- [] New feature - about page

# How this has been tested✅

on dev server

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (532)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Pls fix the contact page as it went up after your changes @praptisharma28

**Comment by praptisharma28** [comment]
yes @Rakesh9100 wait

**Comment by Rakesh9100** [comment]
image

Include some good fa-icon for about menu item @praptisharma28

**Comment by Rakesh9100** [comment]
image

Include some good fa-icon for `About` menu item @praptisharma28

**Comment by praptisharma28** [comment]
done @Rakesh9100

**Comment by praptisharma28** [comment]
Also @Rakesh9100 look at this issue https://github.com/Rakesh9100/Beautiify/issues/379

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under 🎉🎉 @praptisharma28

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @praptisharma28

**Pull request merged**
