### PR TITLE
Added Neuromorphism Background

### LINKED ISSUE #2: Neuromorphism Background
Add a neuromorphism background inside Backgrounds components.

### PR DESCRIPTION
**Pull request by itsmeabhishek03**
# Fixes Issue🛠️

Closes #2 

# Description👨‍💻 
Added Neuromorphism Background using HTML, CSS and JAVASCRIPT

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

It is a very simple website with html css and javascript so just click on open with live server to test it. 

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add neuromorphism background instead of adding neuromorphism card or neuromorphism form @itsmeabhishek03

**Comment by itsmeabhishek03** [comment]
> Pls add neuromorphism background instead of adding neuromorphism card or neuromorphism form @itsmeabhishek03

hey @Rakesh9100 is this fine ?

image

**Comment by Rakesh9100** [comment]
Better than previous one. Do the commit @itsmeabhishek03 

Also, complete and create PRs of every issues assigned to you in other projects as well.

**Comment by itsmeabhishek03** [comment]
> Better than previous one. Do the commit @itsmeabhishek03
> 
> Also, complete and create PRs of every issues assigned to you in other projects as well.

ok, yes working on it

**Comment by Rakesh9100** [comment]
Make the commit of this so that I can merge or are you still working on this @itsmeabhishek03

**Review by banidoru — CHANGES_REQUESTED** [review]
- The new unit tests are a welcome addition and improve coverage.
- However, none of the five substantive issues from the previous review have been addressed.
- Key counters are still incremented incorrectly, and suggested refactorings have not been implemented.

**Pull request closed without merging**
