### PR TITLE
Highlighted the active menu item of navbar

### LINKED ISSUE #349: [Feature] Highlight the active menu item of navbar
### Description

When we open contact ,home or any other page it does not highlight which page we are on currently . 

### Screenshots

Screenshot 2024-01-20 at 9 02 30 PM

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️

Closes #349 

# Description👨‍💻 

Highlight the active menu item of navbar 

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/125949765/49538cca-3c64-4593-80ad-17b07566be7b

### CODE REVIEW

**Comment by AftabMankapure** [comment]
check this PR

**Comment by Rakesh9100** [comment]
When we click on `Components` button of the navbar, it should become red @AftabMankapure

**Comment by AftabMankapure** [comment]
check now

**Comment by Rakesh9100** [comment]
We already have seperate `script.js` file, so place your code in that file instead of html file @AftabMankapure

**Comment by Rakesh9100** [comment]
We already have separate `script.js` file, so place your code in that file instead of html file @AftabMankapure

**Comment by AftabMankapure** [comment]
check it now

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @AftabMankapure

**Pull request merged**
