### PR TITLE
Added Logo in Navbar

### LINKED ISSUE #307: [Feature] Adding Logo in Navbar
### Description

I would like to add logo in left side of the web page .Please assign this issue to me

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by vishapraj**
# Fixes Issue🛠️

Closes #307 

# Description👨‍💻 
I have created a flex box and in right side I put app name and in left side logo.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by vishapraj** [comment]
@Rakesh9100 pls review my PR

**Comment by Rakesh9100** [comment]
Mention the issue number, write about your changes and add screenshots of your changes in the PR description @vishapraj

**Comment by vishapraj** [comment]
issue no. 307
actually I have created a flex box and in right side I put app name and in left side logo

**Comment by Rakesh9100** [comment]
Upload your screenshot properly and work on the change in the PR description made in the comment above @vishapraj

**Comment by vishapraj** [comment]
I have done changes and added logo in navbar

**Comment by Rakesh9100** [comment]
> Upload your screenshot properly and update the PR description @vishapraj

Read this properly else I will close the PR and unassign you @vishapraj

**Comment by Rakesh9100** [comment]
Merged, Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @vishapraj

**Pull request merged**
