### PR TITLE
Added Liquid button

### LINKED ISSUE #91: Add a Liquid button
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a liquid button, please assign it to me under SWOC'24

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by rishicds**
# Fixes Issue🛠️

Closes #91 

# Description👨‍💻 

Added a liquid button that changes shape when you hover on it

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls keep the button to center of the screen @rishicds

**Comment by rishicds** [comment]
Done, please check @rishicds

**Comment by Rakesh9100** [comment]
Its not in the center, it should be centered vertically as well @rishicds 

image

**Comment by rishicds** [comment]
please check now, it was centered on my screen from all sides thats why it was a bit hard for me to debug @Rakesh9100

**Comment by Rakesh9100** [comment]
Done, Merged!! 🎉 @rishicds

**Comment by Rakesh9100** [comment]
Button looks pretty nice!! ✨ @rishicds

**Comment by rishicds** [comment]
Thank you 😄 @Rakesh9100

**Comment by GhoshAditi** [comment]
@rishicds  such a beautiful button

**Comment by rishicds** [comment]
Thank you @GhoshAditi 😊

**Pull request merged**
