### PR TITLE
Added Timeline Card

### LINKED ISSUE #198: Adding a new Timeline Card
### Description

It will have a Interactive card that displays a timeline of events. Pls assign me this under IWOC @ 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Dhairya1Gupta**
# Fixes Issue🛠️

Closes #198

# Description👨‍💻 

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

- Added a Timeline Card under cards section

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
timeline_card

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Why clock-Loader file changes and commits are shown @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
> Why clock-Loader file changes and commits are shown @Dhairya1Gupta

Sir those are previous commits @Rakesh9100

**Comment by Dhairya1Gupta** [comment]
> Why clock-Loader file changes and commits are shown @Dhairya1Gupta

Fixed the issue please review @Rakesh9100

**Comment by Dhairya1Gupta** [comment]
> Why clock-Loader file changes and commits are shown @Dhairya1Gupta

Working on this issue @Rakesh9100

**Comment by Dhairya1Gupta** [comment]
Working on new PR pls standby @Rakesh9100

**Pull request closed without merging**
