### PR TITLE
Added Preloader

### LINKED ISSUE #100: Adding a Preloader to the main website
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Using a loading animation can make the website look nicer and improve how people enjoy using it.

Can do it using simple javascript and GASP 

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Vikranthraosb**
# Fixes Issue🛠️

Closes #100

# Description👨‍💻 
Added a preloader to the website

# Type of change📄

- [✅] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [✅ ] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my own code
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [✅ ] I have added demonstration in the form of GIF/video file
- [✅ ] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/102306707/a8a8fe0d-de7d-4c97-88b1-1be2d5e641f7

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Don't do changes in main `index.html`, `style.css` and `script.js` files. Instead create seperate loader.html and so on files in assets folder and link to the main files @Vikranthraosb

**Comment by Rakesh9100** [comment]
Resolve the conflicts and why 73 files are shown as changed, do fix @Vikranthraosb

**Comment by Vikranthraosb** [comment]
> Resolve the conflicts and why 73 files are shown as changed, do fix @Vikranthraosb

**Comment by Vikranthraosb** [comment]
hi, can I add only html code of preloader(7-8 line) in index.html? i've made seperate css and js files but since preloader loades automatically, I am not able to link it by button or anchor tag.

If not you can close pull request.

Thank you.

**Comment by Rakesh9100** [comment]
Yes, if you have created seperate files then you can add some lines of code to `index.html` file

But fix these, why so many  file changes are coming @Vikranthraosb 
image

**Pull request closed without merging**
