### PR TITLE
Added Triangle Loader

### LINKED ISSUE #464: [Feature] Animated triangle loader
### Description

Adding an animated triangle loader under loaders component

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by bhavya-anand19**
# Fixes Issue🛠️

Closes #464 

# Description👨‍💻 

Added a triangle loader under loaders component
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# This has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/133582773/37913187-40e7-45fe-bbfb-809118d5d054

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Remove any other extra changes in `loaers.html` file and just keep your component addition @bhavya-anand19

**Comment by Rakesh9100** [comment]
Remove any other extra changes in `loaders.html` file and just keep your component addition @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Remove any other extra changes in `loaders.html` file and just keep your component addition @bhavya-anand19
> 
> And attach demo video properly in PR description!!

Done

**Comment by Rakesh9100** [comment]
No extra changes should come, fix it @bhavya-anand19 

image

**Comment by bhavya-anand19** [comment]
> No extra changes should come, fix it @bhavya-anand19
> 
> image

done

**Comment by Rakesh9100** [comment]
Merged 🎉 @bhavya-anand19

**Pull request merged**
