### PR TITLE
Change home page style and added 3D UI ISSUE #22

### LINKED ISSUE #22: GIve it 3D UI Home Page by manipulating Shadows and depths
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

GIve it 3D UI Home Page by manipulating Shadows and depths .
->Manipulating shadows with minute border and dark background will make it look professional and 3D.

Kindly assign me this issue under SWOC24 @Rakesh9100 

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by raghav1482**
# Fixes Issue🛠️
GIve it 3D UI Home Page by manipulating Shadows and depths

Closes #22

# Description👨‍💻 

Added 3D effect on image and cards along with minimal UI changes.

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Ran on localhost, 

# Checklist✅ 

- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have added demonstration in the form of GIF/video file
- [y] I am an Open Source Contributor

# Screenshots/GIF📷
ezgif-4-9081e28e69

### CODE REVIEW

**Comment by raghav1482** [comment]
@Rakesh9100  Kindly review my PR #24 .

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @raghav1482

**Comment by raghav1482** [comment]
@Rakesh9100 kindly review my PR #24 i have resolved the conflicts

**Comment by Rakesh9100** [comment]
Looks good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🥳🎉 @raghav1482

**Pull request merged**
