### PR TITLE
Added Payment Form

### LINKED ISSUE #209: Adding Payment Form in Forms category
### Description

@Rakesh9100  I would like to work on this under JWOC

### Screenshots

Screenshot 2024-01-15 001043

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prithwi32**
# Fixes Issue🛠️

Closes #209 

# Description👨‍💻 
I have included Payment Form to project so that it can be used in transaction websites.

# Type of change📄
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I have tested the correct working of my form using live server of vscode.

# Checklist✅ 
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls follow the PR template and edit the PR description @Prithwi32

**Comment by Prithwi32** [comment]
> # Fixes Issue🛠️
> Closes #209
> 
> # Description👨‍💻
> I have included Payment Form to project so that it can be used in transaction websites.
> 
> # Type of change📄
> * [] New feature (non-breaking change which adds functionality)
> 
> # How this has been tested✅
> I have tested the correct working of my form using live server of vscode.
> 
> # Checklist✅
> * [] My code follows the style guidelines of this project
> * [] I have performed a self-review of my own code
> * [] I have commented my code, particularly in hard-to-understand areas
> * [] I have added demonstration in the form of GIF/video file
> * [] I am an Open Source Contributor
> 
> # Screenshots/GIF📷
> Screenshot

@Rakesh9100  Could check this once now

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Prithwi32

**Comment by Prithwi32** [comment]
> Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Prithwi32

Thank you so much sir :)

**Pull request merged**
