### PR TITLE
Enhanced the Beautiify heading

### LINKED ISSUE #770: [Style] Enhance the Beautiify heading
### What's the style idea?

We need to improve { Beautiify } heading in animation form like text color animation effect 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sheetal-81**
# Fixes Issue🛠️

Closes #770 

# Description👨‍💻

- The heading was previously simply styled.
- This has been corrected to ensure it is properly displayed and enhances the overall user experience.
- Applied animation: An animation effect has been added to the heading to make it more dynamic and engaging. This change enhances the visual appeal of the page.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/134307985/2f19c6f2-9f2c-4eed-a259-998068bc58e0

### CODE REVIEW

**Comment by sheetal-81** [comment]
i have completed the task of **Enhance the Beautiify heading** even push also pls look into it

**Comment by Rakesh9100** [comment]
Pls mention the issue number for this PR, edit the PR description above and fill all the details properly.
Also, attach the screenshots of your work @sheetal-81

**Comment by sheetal-81** [comment]
Done @Rakesh9100 pls do check and let me know what else i can do

**Comment by Rakesh9100** [comment]
I am asking the issue number which you are assigned to @sheetal-81

**Comment by sheetal-81** [comment]
can i assume it is complete now ? Or do i have to apply more changes .
@Rakesh9100

**Pull request merged**
