### PR TITLE
Added Floating Action Button (FAB) Navigation Bar

### LINKED ISSUE #1029: [Feature] Add Floating Action Button (FAB) Navigation Bar
### Description

A navigation bar inspired by mobile design, featuring a floating action button that expands into a radial menu when clicked. This is particularly useful for mobile-first designs.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sanayamahajan-23**
# Fixes Issue🛠️

Closes #1029 

# Description👨‍💻

I added new kind of navbar named floating action button navbar which works when clicked on button it spreads out the navbar icons and also highlights the active icon.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls work on these by making new commits in this same PR, don't close this PR @sanayamahajan-23 

1. Rename your folder to `Floating-Action-Button-Navigation-Bar` and make the changes accordingly.
2. Add your component part in the `navigation-bars.html` file to display on the website.

**Comment by sanayamahajan-23** [comment]
added the said things

**Comment by Rakesh9100** [comment]
image

### Place it on the top instead of down the screen as it is the navbar @sanayamahajan-23

**Comment by sanayamahajan-23** [comment]
@Rakesh910 moved the navbar up instead of bottomction,

**Pull request merged**
