### PR TITLE
Succesfully solved issue : The Heading H1 and H3 will not show under …

### PR DESCRIPTION
**Pull request by Akshatverma01**
…navbar

# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Which issue you are working for? @Akshatverma01

**Comment by Rakesh9100** [comment]
Pls get the issue assigned before creating a PR. You are not assigned to any issue @Akshatverma01

**Comment by Akshatverma01** [comment]
> Pls get the issue assigned before creating a PR. You are not assigned to any issue @Akshatverma01

Yeah but I solved the issue and created a pull request to you.

**Comment by Rakesh9100** [comment]
Yes, the person who opens issue will be assigned @Akshatverma01

**Comment by Akshatverma01** [comment]
Okay. Actually I saw other made a PR and asking admin to merge it and they
merged it.

**Pull request closed without merging**
