### PR TITLE
Improved hover effect for the buttons on the navbar

### LINKED ISSUE #404: [Style] Improve hover effect for the buttons on the navbar
### What's the style idea?

The current hover effects and animations for the nav-bar do not look complete or proper. I can improve the nav-bar drastically in terms of look and feel.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️ #404 

Closes #404 

# Description👨‍💻 

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Nhover

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Rakesh9100** [comment]
1. Implement some good hover effect.
2. On hovering navbar should remain smooth and should not move up or down. @AftabMankapure

**Comment by AftabMankapure** [comment]
https://github.com/Rakesh9100/Beautiify/assets/125949765/94b6c1b7-8cff-4f43-b28b-28d55134874e

@Rakesh9100  i try many of navbar hover effect but when i apply to navbar then navbar link is not working 
for new hover effect we need to complete rewrite navbar code  it take time i can do it just add  HARD label

**Comment by Rakesh9100** [comment]
Label will be added depending on the work you will do, you have to add some better hover effect @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  i creating  new pull request pls check this
so i close this

**Pull request closed without merging**
