### PR TITLE
update footer

### LINKED ISSUE #30: Adding Footer
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Please allow me to add interactive footer.
social medial links , contact us and Site logo or name

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by vishal0316**
# Fixes Issue🛠️

Closes #30 

# Description👨‍💻 

Added interactive footer with social media links.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

# How this has been tested✅

Simply run index.html and check footer

# Checklist✅ 

- ✅My code follows the style guidelines of this project
-✅ I have performed a self-review of my own code
- ✅ I have commented my code, particularly in hard-to-understand areas
- ✅I have added demonstration in the form of GIF/video file
- ✅I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
We don't need this big footer. You can just add more social icons in the exisitng footer and just put hover animations on it @vishal0316

**Comment by vishal0316** [comment]
> We don't need this big footer. You can just add more social icons in the exisitng footer and just put hover animations on it @vishal0316 

ok sure i will do it

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @vishal0316 
Don't close the PR, just pull the latest changes on your fork.

**Comment by vishal0316** [comment]
Some how pull request is closed what should I do now?

**Comment by vishal0316** [comment]
Reopen pull request

**Comment by Rakesh9100** [comment]
First pull the latest changes of the repo and then make your changes accordingly and create a PR @vishal0316

**Comment by vishal0316** [comment]
> First pull the latest changes of the repo and then make your changes accordingly and create a PR @vishal0316

done you can check

**Pull request closed without merging**
