### PR TITLE
Added Box Loader

### LINKED ISSUE #83: Add Box Loader
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Wanted to add a new loader in component as it has only 2 loading component and i wanna add one more to it .
 I have attached the image of loader.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by chanda-04**
# Fixes Issue🛠

Closes #83

# Description👨‍💻 

Added a new Loader in the component section.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-12 225728

### CODE REVIEW

**Comment by chanda-04** [comment]
Created a pull request and here is link: https://github.com/Rakesh9100/Beautiify/pull/169

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @chanda-04

**Comment by Rakesh9100** [comment]
Are you working @chanda-04

**Comment by chanda-04** [comment]
Can you please open this Issue and PR again?

**Comment by Rakesh9100** [comment]
Opened this time but abide by the rules of open source.

Merged, Congrats on getting your PR merged to this repo under SWOC S4 🎉 @chanda-04

**Comment by chanda-04** [comment]
sure thanks :)

**Pull request merged**
