### PR TITLE
Added Cup Loader

### PR DESCRIPTION
**Pull request by divyansh2375**
# Fixes Issue🛠️

#66 
Added the Cup Loader 

Closes #

# Description👨‍💻 

i have added the new style of loader whose name is Cup loader

# Type of change📄

Enhancement

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

image

image

# Screenshots/GIF📷

### CODE REVIEW

**Comment by divyansh2375** [comment]
@Rakesh9100  I have successfully created the Cup Loader Please review my PR.

**Comment by Rakesh9100** [comment]
Pls mention the issue number this PR closes.

Delete other image files as you have used only `liquid2.jpeg` in your code as I can see.

Name this liquid2.jpeg to liquid.jpeg after deleting extra  images @divyansh2375

**Comment by divyansh2375** [comment]
@Rakesh9100  can you please tell me where can i find the issue number?

**Comment by divyansh2375** [comment]
@Rakesh9100 I have Updated . can you please review again

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @divyansh2375

**Comment by divyansh2375** [comment]
Thank you @Rakesh9100 for merging it i would like to solve more issues

**Pull request merged**
