### PR TITLE
Enhanced the components category in home page

### LINKED ISSUE #747: [Style] Enhance the components category in home page
### What's the style idea?

We need to improve 
by adding new color components to make the user feel good and attract them to use the website again and again, leading to a better user experience. 
Making the components transparent doesn't look good. Colors like white and black are mandatory to give a classic look to the website.
I have a good grasp of CSS styling. I have created many clones and developed my own website, OvenOasis. I have a good command of coloring ratios and I am confident that I can make this website more attractive.
 Please assign this project to me under GSSOC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Mdazar123**
# Fixes Issue🛠️

Closes #747 

# Description👨‍💻

The hover effect styling and color combinations in the components category section have been enhanced.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot from 2024-06-21 09-27-10

Screenshot from 2024-06-21 09-27-00

### CODE REVIEW

**Comment by Mdazar123** [comment]
Hi @Rakesh9100 ,
if orange color dosen't look good here is the anthor design for components section.
Screenshot from 2024-06-21 00-23-07

**Comment by Rakesh9100** [comment]
Pls mention the issue number in the PR description which you are assigned to @Mdazar123

**Comment by Rakesh9100** [comment]
Pls mention the issue number in the PR description which you are assigned to!

Implement the second color and remove the orange @Mdazar123

**Comment by Rakesh9100** [comment]
Pls mention the issue number in the PR description which you are assigned to!

Implement the second color and remove the orange by making the new commit in this same PR, don't close this @Mdazar123

**Comment by Mdazar123** [comment]
Hi @Rakesh9100,

being a newbie to open source ,I'm not sure how to commit changes to the same pull request (PR). I accidentally created another PR with the same branch, #1117.

Thank you!

**Comment by Rakesh9100** [comment]
This you should have asked me before, as I clearly mentioned to not create new PR. You have to learn to how to make new commits in opened PR and that is why these open source programs are there @Mdazar123

**Comment by Mdazar123** [comment]
Hi @Rakesh9100,

I apologize for my mistake. I thought it would be committed in the same PR, but it generated a new one. 
What should I do now? Also, could you please let me know how to commit in the same PR?

**Comment by Mdazar123** [comment]
Hi @Rakesh9100,

Please give me a chance to correct my mistake. Due to a strict schedule of classes, assignments, and exams, I was unable to focus completely on contributions.

**Comment by Rakesh9100** [comment]
No problem. Since you're new to contributions, you can learn to make new commits in the same open PR using web resources and GPTs. Additionally, familiarize yourself with git commands, how to resolve merge conflicts, and other related topics to assist you in making open source contributions @Mdazar123

**Comment by Mdazar123** [comment]
Hi @Rakesh9100 ,

thank you so much for accepting my PR.

**Pull request merged**
