### PR TITLE
About us page made responsive

### LINKED ISSUE #539: [Bug] About us page is not responsive
### Description

the about us page is not responsive when we open in cell phone text get overlaped 

### Screenshots

(2) WhatsApp - Google Chrome 06-02-2024 13_40_39

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️ #539 

Closes #539 

# Description👨‍💻 

made About us page is  responsive #539

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
ab

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Rakesh9100** [comment]
Don't change the main UI, you have to make properly responsive for small screens without altering the UI of larger screens @AftabMankapure

**Comment by AftabMankapure** [comment]
pls check now

**Comment by AftabMankapure** [comment]
check this PR

**Comment by AftabMankapure** [comment]
@Rakesh9100  any issue in PR

**Comment by Rakesh9100** [comment]
Merged 🎉 @AftabMankapure

**Pull request merged**
