### PR TITLE
Footer overflowing in contributors page fixed

### LINKED ISSUE #289: [Bug] Footer overflowing in contributors page on small screen
### Description

The footer on the contributor page overlaps the Contributor section making merged visibility of both sections in smaller screens.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pb0126**
# Fixes Issue🛠️

Closes #289 

# Description👨‍💻 

The footer was over lapping with contributors' cards due to which the content visibility was compromised. The footer has been fixed and restored to its original place

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Major checks have been made using Chrome developer tools in all sizes of screens.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Before:-
image

image

After:-
image

image

### CODE REVIEW

**Comment by pb0126** [comment]
Hi, @Rakesh9100 PLease verify the changes and merge the pr into main branch
Thanks

**Comment by Rakesh9100** [comment]
image

Pls remove the spaces below the footer @pb0126

**Comment by pb0126** [comment]
Okay

**Comment by pb0126** [comment]
Hi @Rakesh9100, Please check now, also assign me issue #291

**Comment by Rakesh9100** [comment]
Not fixed, check again and resolve @pb0126

**Comment by pb0126** [comment]
image

**Comment by Rakesh9100** [comment]
image

@pb0126

**Comment by pb0126** [comment]
Please check again

**Comment by Rakesh9100** [comment]
Yes done, netlify didn't updated  that I think @pb0126

**Pull request merged**
