### PR TITLE
Enhanced the 404 error page

### LINKED ISSUE #1208: [Style] Enhance the 404 error page
### What's the style idea?

We need to improve

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Damini2004**
# Fixes Issue🛠️

Closes #1208 

# Description👨‍💻

404 Page updated.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Damini2004** [comment]
@Rakesh9100 Assign suitable level or if any changes required tell me.

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
404 page enhancement done

**Comment by Damini2004** [comment]
@Rakesh9100 @saurabhsingh720   Kindly merge it because gssoc going to end soon.

**Comment by Rakesh9100** [comment]
https://deploy-preview-1254--beautiify.netlify.app/ab

Pls check this deploy preview, the navbar and footer is distorted. Also, instead of logo that was before, you have to put your small png animated gif with no background @Damini2004

**Comment by Rakesh9100** [comment]
Are you working @Damini2004

**Comment by Damini2004** [comment]
Yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Make the commits by today @Damini2004

**Pull request closed without merging**
