### PR TITLE
Added search icon in every search bar

### LINKED ISSUE #820: [Feature] Add search icon in every search bar
### What would you like to share?

We can add search icon in every search bar which enhance user experience, and it will look good.

### Additional information

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by soniya-malviy**
# Fixes Issue🛠️

Closes #820 

# Description👨‍💻 

Added search icon where user will search Component Name (placeholder: Enter Component Name).

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### Before the PR:
Image 30-05-24 at 6 25 PM

### After the PR:
Image 30-05-24 at 6 25 PM (1)

### CODE REVIEW

**Comment by soniya-malviy** [comment]
Successfully add the search icon.

**Comment by soniya-malviy** [comment]
> Pls add to every components category pages as well @soniya-malviy

sure.Rakesh9100.

**Comment by soniya-malviy** [comment]
yes sir , solved in PR #849
please review the PR.

thank you!

**Comment by saurabhsingh720** [comment]
@soniya-malviy 
Check responsiveness of that icon.

**Comment by Rakesh9100** [comment]
Yes, the icon is not responsive as well as the website is distorted @soniya-malviy

**Pull request closed without merging**
