### PR TITLE
Added Overlay navbar

### LINKED ISSUE #173: [Feature] Overlay Navigation Bar
### Description

I want to add an overlay navigation bar in your navbar collections .!!

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #173 

# Description👨‍💻 
Here , in overlay nav bar when we click at open overlay it turns out a navbar with descriptive pages , and it is also responsive 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attacht he screenshot in the PR description and write about the work you have done under Description section @AbhineshJha

**Comment by Rakesh9100** [comment]
Pls attach the screenshot in the PR description and write about the work you have done under Description section @AbhineshJha

**Comment by AbhineshJha** [comment]
done sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @AbhineshJha

**Pull request merged**
