### PR TITLE
Added Crazy Arch Loader

### LINKED ISSUE #892: [Feature] Add Crazy Arch Loader
### Description

To add few components
    Crazy Arch Loaders
    Cuboid Loader
    Minimalist Loader
    Drag and Drop Loader
    Animated moon background
Please assign me this work.

### Screenshots

[Screencast from 2024-06-05 01-51-01.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/ed8b19df-aa4a-4980-97ab-9bcdd25d45bb)

[Screencast from 2024-06-05 01-51-39.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/b1e736f5-40f5-4faf-9ed1-c2c1803ca433)

[Screencast from 2024-06-05 01-55-24.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/7e57f5a8-91f7-4d59-8b2a-0bd1cec57f81)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by patelkiran185**
# Fixes Issue🛠️

 

Closes #892 

# Description👨‍💻 
It is an loader component named Crazy Arch loader.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested in chromium,brave and firefox browser
# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
[Screencast from 2024-06-08 09-42-22.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/bd7b0e47-2171-4897-ab14-203317a5e044)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Crazy-Arch-Loader` and make the necessary changes in this same PR by making the new commits!

Also add your component in `assets/html_files/loaders.html` file to display on the website @patelkiran185

**Comment by patelkiran185** [comment]
@Rakesh9100 I have made the necessary changes. Kindly review the PR.

**Comment by Rakesh9100** [comment]
Rename your folder correctly as I have mentioned @patelkiran185

**Comment by patelkiran185** [comment]
@Rakesh9100 Kindly review the PR

**Comment by patelkiran185** [comment]
@Rakesh9100 Kindly review the PR.

**Comment by patelkiran185** [comment]
@Rakesh9100 Kindly review the PR.

**Comment by patelkiran185** [comment]
@Rakesh9100 ?

**Pull request merged**
