### PR TITLE
Added Toggle Button-2

### LINKED ISSUE #899: [Feature] Add Toggle Button-2
### Description

adding the source code for dark/light mode toggle button in the navigation bars componets

### Screenshots

toggle button

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Vikashchou-dhary**
# Fixes Issue🛠️

Closes #899 

# Description👨‍💻

I have added the toggle button for dark/light background theme.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

light mode

dark mode

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Why have you added your component in backgrounds if it is a toggle button @Vikashchou-dhary

**Comment by Vikashchou-dhary** [comment]
although it is a button but as it is used to change the background color so i added in the background category

**Comment by Vikashchou-dhary** [comment]
@Rakesh9100  if it is not ok with the background section than i request that the  toggle button which i have requested to merge has better UX than the toggle button in button section so i request to merge it in place of toggle button in the button section

**Comment by Rakesh9100** [comment]
Rename your folder to `Toggle-Button-2` and make the necessary changes in this same PR.

Also, add your button part in the `buttons.html` file to display on the website @Vikashchou-dhary

**Comment by Rakesh9100** [comment]
1. Rename your folder to `Toggle-Button-2` and make the necessary changes in this same PR.
2. Attach the screenshots of your work.
3. Also, add your button part in the `buttons.html` file to display on the website @Vikashchou-dhary

**Comment by Vikashchou-dhary** [comment]
toggle 2
light mode
dark mode

**Pull request merged**
