### PR TITLE
Added contact details in the footer

### LINKED ISSUE #626: [Feature] Add contact details in the footer
### Description

Footer becomes more interactive to user by adding contact us along with social media links of Beautilify.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AlaynaShaheen**
# Fixes Issue🛠️

Closes #626 

# Description👨‍💻 

Added message us section and contact details in footer.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### Mobile view:

Screenshot 2024-06-07 194404

Screenshot 2024-06-07 194412

### Desktop view:

Screenshot 2024-06-07 194427

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls provide your suggestions on this @saurabhsingh720

**Comment by saurabhsingh720** [comment]
@AlaynaShaheen 
Looking good but try to match the UI colour.

**Comment by AlaynaShaheen** [comment]
Sorry I forgot to check that @saurabhsingh720. Please review this and let me know if there are any further changes.
Screenshot 2024-06-08 183929

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Now it looks cool.
U can merge .

**Comment by Rakesh9100** [comment]
You can make the footer similar as you have made in CalcDiverse project and match the UI properly @AlaynaShaheen

**Comment by Rakesh9100** [comment]
Sorry for the late response, you can make the footer similar as you have made in CalcDiverse project and match the UI properly @AlaynaShaheen

**Comment by Rakesh9100** [comment]
Are you working @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
@Rakesh9100 Sorry for the delay, I was having semester exams last week. I have now started working on this issue and will raise a PR soon.

**Comment by Rakesh9100** [comment]
Okay @AlaynaShaheen

**Pull request closed without merging**
