### PR TITLE
Enhanced the website with Chakra UI

### LINKED ISSUE #637: [Style] Enhance the website with Chakra UI
### What's the style idea?

Buttons on the website appear dull and lack visual appeal. Implementing Chakra UI can breathe new life into button design, providing a sleeker and more modern appearance.
These changes will not only improve the overall aesthetics of the website but also enhance user experience and security.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Leorasaharia**
# Fixes Issue🛠️

Closes #637 

# Description👨‍💻 

I have made the following enhancements to the buttons:

- Improved the color scheme for better aesthetics and readability.
- Updated the appearance to give the buttons a more modern and chic look.
- Changed the font scheme to better align with the overall design

# Type of change📄

- [x] New feature (non-breaking change which adds functionality) (Color scheme of buttons was changed)

# How this has been tested✅

Tested locally.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/143778430/56ca97f4-1da4-405e-b256-ec5b26296934

### CODE REVIEW

**Comment by Leorasaharia** [comment]
@Rakesh9100 do let me know if it's alright or do i need to make other changes too

**Comment by Rakesh9100** [comment]
image

image

image

image

image

## Why are you adding these all two times, you should make changes to the existing code only and structure the code! Those are already defined, pls make your changes to the existing ones only!! @Leorasaharia

**Comment by Leorasaharia** [comment]
By the way, I just noticed that you haven't given me any GSSoC label or any level.

**Comment by Leorasaharia** [comment]
@Rakesh9100, I added those lines because, as mentioned in the issue, some of the fonts and the color scheme, along with the display of these buttons, needed enhancement. They were too blurry previously, which is why I wrote some new lines. If I remove those lines, it will revert to how it was before.

**Comment by Rakesh9100** [comment]
But what the need to give again new variables for the same. For example body tag, it is already defined before, if you want to let's say change color in that, you can mention in that only. No need to again create body{} tag and define your attribute in that @Leorasaharia

**Comment by Leorasaharia** [comment]
Okay i'll modify it

**Review by Leorasaharia — COMMENTED** [review]
@Rakesh9100 removed the duplicates

**Comment by Leorasaharia** [comment]
@Rakesh9100 kindly review my pr.

**Pull request merged**
