### PR TITLE
Added Infinite Carousel

### LINKED ISSUE #264: [Feature] Infinite Carousel
### Description

An infinite carousel which runs at uncountable iterations of images 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/97e2bb3e-91ca-4747-a555-1b5dc264f68c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #264 

# Description👨‍💻 

Added Infinite carousel which has infinite no.s of sliding images .

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/142514166/6078e3cb-8c90-4468-9186-245d632b7ed4

### CODE REVIEW

**Comment by AbhineshJha** [comment]
Please review @Rakesh9100

**Comment by Rakesh9100** [comment]
Can I know why have you created a second PR for the same issue @AbhineshJha

**Comment by AbhineshJha** [comment]
Basically the webkit of css i used have issue , and when i wanted to access my branch it says that your all files are untracked
something like this 
image
Then i have to add -webkit-mask then create another branch for pushing the code

**Comment by Rakesh9100** [comment]
Keep the files of Infinite Carousel only in this PR @AbhineshJha

**Comment by AbhineshJha** [comment]
As I said earlier, it's GitHub ui , when I raise pr on the same time then the last one reflects ui of both, but you can navigate the file/folder by using the *commit* @Rakesh9100

**Comment by Rakesh9100** [comment]
When working on creation of two new PRs at same time, first thing is to create both in different branches and make different commits for that particular branch.
Secondly, if your commits of first PR are also shown in second PR which should not happen, stage those changes and then proceed forward @AbhineshJha 

So fix this issue and resolve this conflicts @AbhineshJha

**Comment by AbhineshJha** [comment]
Sir @Rakesh9100  i did the same for different features , i created different branches and staged and push with different branches .!
And after searching this is what i get : 
image

**Comment by AbhineshJha** [comment]
hey @Rakesh9100 !! Thank you for compromising with my mistake. I learnt new things not just this, i learnt many more just because of you!!😊

**Pull request merged**
