### PR TITLE
Added Scrolling Text Animation

### LINKED ISSUE #787: [Feature] Add Loading Text Animation & Gradient Background
### Description

I would like to suggest adding two new components to enhance the visual appeal and user experience of the website: a loading text animation in the text animation section and a gradient background in the background section.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by amandollar**
# Fixes Issue 🛠️

Closes #787 

# Description 👨‍💻

Added scrolling text animation in the text animation section of the website. The animation scrolls from right to left.

# Type of change 📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested ✅

Tested the scrolling text animation by checking the website in different browsers and screen sizes to ensure it behaves as expected.

# Checklist ✅

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF 📷

Scrolling Text

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls mention the issue number for which you have created this PR @amandollar 

Pls check these things @saurav2208

**Comment by Rakesh9100** [comment]
Pls mention the issue number for which you have created this PR @amandollar 

Pls check these things @saurabhsingh720

**Comment by amandollar** [comment]
Issue number 
#787

**Comment by saurabhsingh720** [comment]
> Pls mention the issue number for which you have created this PR @amandollar
> 
> Pls check these things @saurabhsingh720

Ok

**Comment by Rakesh9100** [comment]
You have opened issue to add 2 components, but I can see only 1 in this PR and that also it is Scrolling text animation, but issue is describing Loading Text Animation @amandollar

**Comment by Rakesh9100** [comment]
You have opened issue to add 2 components, but I can see only 1 in this PR and that also it is Scrolling Text Animation, but issue is describing Loading Text Animation @amandollar

**Comment by Rakesh9100** [comment]
Will close this PR by EOD if no update today @amandollar

**Pull request closed without merging**
