### PR TITLE
Added Order Cancellation Form

### LINKED ISSUE #886: [Feature] Add Order Cancellation Form
## Description 
An Order Cancellation Form is a document used by customers to formally request the cancellation of an order they have previously placed. This form helps both the customer and the seller to clearly document and process the cancellation request, ensuring that all necessary details are captured for the transaction to be terminated efficiently.

## About
The Order Cancellation Form typically includes the following sections:

1. Customer Information:
2. Order Details:
3. Cancellation Details:
4. Confirmation:

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
# Fixes Issue🛠️

Closes #886 

# Description👨‍💻

I have added the order cancelation form, which included 
The Order Cancellation Form typically includes the following sections:

1. Customer Information:
2. Order Details:
3. Cancellation Details:
4. Confirmation:

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image_2024-06-08_230713811

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@Rakesh9100  please will you merge this pr

**Comment by Rakesh9100** [comment]
image

Give some margin at the top and enhance the UI accordingly, also center the heading @Pujan-sarkar

**Comment by Rakesh9100** [comment]
image

### Give some margin at the top and enhance the UI accordingly, also center the heading @Pujan-sarkar

**Comment by Pujan-sarkar** [comment]
@Rakesh9100  now check it

**Comment by Pujan-sarkar** [comment]
@Rakesh9100  please check it

**Pull request merged**
