### PR TITLE
Added the Chatbot

### LINKED ISSUE #156: Adding a chatbot
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This issue is regarding a chatbot that will further explain the components or any doubt regarding the website for making it more user friendly website

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by manya975**
# Fixes Issue🛠️

Closes #156 

# Description👨‍💻 

I have added the chatbot.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots 📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Is this chatbot answering this website `Beautiify` questions? @manya975

**Comment by manya975** [comment]
@Rakesh9100 Yes it is

**Comment by Rakesh9100** [comment]
Pls provide some examples(3-4) screenshots answering the questions of this website @manya975

**Comment by manya975** [comment]
These are some of the screenshots of questions and their answers.....

image
image
image

Also we can modify this data anytime without any changes in code.

**Comment by Rakesh9100** [comment]
Add some screenshots demo if it can answer about the components present, which components are present on this website and so on.

Also it will be good if you provide a Chatbot.md file under `assets` folder that consist of the steps and guidelines how we can modify this data without changes in code and other informations needed @manya975

**Comment by Rakesh9100** [comment]
Are you working @manya975

**Comment by manya975** [comment]
@Rakesh9100 Yes will complete it by tomorrow

**Comment by manya975** [comment]
These are some more screenshots uder issue #156 and will upload the text file by tomorrow.....
image
image
image

**Comment by Rakesh9100** [comment]
Alright @manya975

**Comment by manya975** [comment]
Hi @Rakesh9100 . I have added the Chatbot text file ..

**Comment by Rakesh9100** [comment]
Can you provide the owner/admin role to my email for your workspace so that I can do any changes anytime when needed @manya975

**Comment by manya975** [comment]
@Rakesh9100 Can you please provide me your mail id for the same.

**Comment by Rakesh9100** [comment]
`roshanrakesh7362@gmail.com` !!

**Comment by manya975** [comment]
Hi @Rakesh9100 An invitation mail was sent to you as I have added you as administrator.

**Comment by Rakesh9100** [comment]
Okay, will check.

Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @manya975

**Comment by manya975** [comment]
Thank You @Rakesh9100. It's my pleasure to contribute in this project.

**Pull request merged**
