### PR TITLE
Added OTP Verification Form & Drag and Drop Form

### LINKED ISSUE #430: [Feature] Adding OTP Verification Form & Drag and Drop Form
### What would you like to share?

I WANT TO ADD 4 FORMS IN THE [ Forms ] PAGE.
Here are the forms ---
1. OTP code verification form - Basic Otp enter and submit form using html css and js.
2. Drag and Drop form - Allow users to drag and drop elements (like files or options) into the form for submission..
3. Text To Voice Converter form - Contains a text area to write texts and later converts it into voice .
4. QR Code generator form - Just enter any url of a website and get a qr code .
5. Modal/ Popup login form - Create a form that pops up in a modal window when a button is clicked..

### Additional information

It is an add-on/enhancement issue raised to contribute under ******JWOC 2024********

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ratnojitsaha**
1 OTP VERI FORM
2 DRAG AND DROP FORM

THIS FORMS ARE MADE USING HTML CSS AND JAVASCRIPT. THE DRAG AND DROP FORM CAN BE IMPLEMENTED TO INSERT ANY TYPE OF FILE MOREOVER IT INDICATES THE TYPE OF FILE(IMAGE, VIDEO AND PDF) INSERTED AND THE NUMBER AND NAME OF THE FILE TOO. IT CONSISTS OF VERY SIMPLE UI.

Closes #430  

JWOC 2024

# Type of change📄 [ENHANCEMENT]

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
1. OTP VERIFICATION FORM - 
Screenshot (529)
Screenshot (533)

2. DRAG AND DROP FORM - 
Screenshot (532)
Screenshot (531)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Rename your folder to `OTP-Verification-Form` and `Drag-And-Drop-Form` respectively and make the necessary changes without closing this PR @ratnojitsaha

**Comment by ratnojitsaha** [comment]
@Rakesh9100 done

**Comment by Rakesh9100** [comment]
Pls look the comment above again and rename the folders exactly same as told @ratnojitsaha

**Comment by ratnojitsaha** [comment]
done

**Comment by Rakesh9100** [comment]
You have not renamed the folders, just changed the forms.html file @ratnojitsaha

**Comment by ratnojitsaha** [comment]
Screenshot (536)
sir according to this ss, I have renamed the folders, by any chance do you mean to change the card name in the forms section which will be displayed in the website?

**Comment by Rakesh9100** [comment]
Check here pls [File Changes](https://github.com/Rakesh9100/Beautiify/pull/573/files)

image

This might be the case that you have updated capitalisation changes on VSCode but it is not getting recognised as changes, so you can do it on your branch on github manually @ratnojitsaha

**Comment by ratnojitsaha** [comment]
Screenshot (538)
@Rakesh9100 Manually done

**Comment by Rakesh9100** [comment]
Looks good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @ratnojitsaha

**Pull request merged**
