### PR TITLE
Added new card: Animated Products Details Card

### LINKED ISSUE #216: [Feature] Add a new type of card [Animated Product Card]
### Description

I want to add. new type of card under the components, An animated Product Card, which shall be useful for E-commerce websites and many more. Please assign me this issue under JWOC'24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/a8985b46-a806-4491-a2a2-31df554bb85f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #216 

# Description👨‍💻 

Added the Animated Product Details Card

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my local machine, works and looks as intended.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/2e7d743f-6350-43b9-a829-683b57dcc09a

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls don't do any changes in `cards.html` file except just adding your component @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Pls don't do any changes in `cards.html` file except just adding your component @SoumyadevSaha

Oh ... I just added my own component only, it's just that the entire cards.html got indented (aligned) by mistake along with it.

**Comment by Rakesh9100** [comment]
Yes, no formatting needed. Do fix @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Yes, no formatting needed. Do fix @SoumyadevSaha

fixed it. please do check once.

**Comment by Rakesh9100** [comment]
Looks good, Merged!! ✨ @SoumyadevSaha

**Pull request merged**
