### PR TITLE
Added Rippling Neumorphic Loader

### LINKED ISSUE #337: [Feature] Adding a Neumorphic Loader
### Description

I want to add a new loader : a neumorphic loader animation. Please assign me this issue under IWOC'24

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/86418216/6a34c401-ed73-41ac-9090-b14b54ad1dd4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #337 

# Description👨‍💻 

Added a neumorphic loader with rippling effect

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on my local machine, works and looks as expected.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Video Demo 📷

https://github.com/Rakesh9100/Beautiify/assets/86418216/758777ff-fc9f-4c18-b811-f2b76a2d953d

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Rippling-Neumorphic-Loder` and make the necessary changes @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Renamed Folder @Rakesh9100

**Comment by Rakesh9100** [comment]
Resolve the conflicts @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Resolved conflicts @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged 🎉 @SoumyadevSaha

**Pull request merged**
