### PR TITLE
Enhanced the website to give new look

### LINKED ISSUE #984: [Style] Enhance the website to give new look
### What's the style idea?

Unleash Your Creativity: A Beautified Experience Awaits!

This exciting update brings a treasure trove of customization options to Beautify, empowering you to craft a truly personalized experience.

* Immerse Yourself: Dive into a world of stunning backgrounds, setting the perfect stage for your content.
* Express Yourself Clearly: Fine-tune text colors for optimal readability and visual appeal. 
* Find Your Voice: Explore a diverse selection of content fonts, allowing you to match the tone and style of your work.
* Embrace Versatility: Experiment with different styles, transforming Beautify to seamlessly integrate with your unique vision.

This is more than just customization – it's a portal to unleash your imagination and craft a Beautify experience that truly reflects you!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Riyaa019**
# Fixes Issue🛠️

Closes #984 

# Description👨‍💻

This pull request introduces a visual refresh for the Beautify website, aiming to enhance user experience and create a more visually appealing aesthetic.

Changes:

* Homepage: Updated the background image and logo to create a fresh first impression.
* Subpages: Consistent background updates applied to all subpages for a cohesive look.
* Content: Refreshed tagline text, colors, and fonts to improve readability and brand alignment.
* Visual Appeal: Enhanced the visual style of boxes and buttons, making them more attractive and user-friendly.

Benefits:

*Improved User Experience: The updated design aims to provide a more engaging and informative experience for visitors.
* Enhanced Brand Consistency: Consistent visuals across the website strengthen brand recognition.
* Increased Visual Appeal: The refreshed design is more visually appealing and reflects the project's value proposition.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot (79)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls mention the issue number for this PR, edit the PR description above and fill all the details properly @Riyaa019

**Comment by Riyaa019** [comment]
Ok I will do the needy and reply to you soon

**Comment by Rakesh9100** [comment]
Do in this same PR, don't create any new PR. You have to edit the PR description @Riyaa019

**Comment by Riyaa019** [comment]
Can you please describe in detail the things I have to mention

**Comment by Riyaa019** [comment]
Here's my Issue number #984

**Comment by Riyaa019** [comment]
Here are the screenshots of changes I have made
Screenshot (79)
Screenshot (81)
Screenshot (82)
Screenshot (83)
Screenshot (86)
Screenshot (84)
Screenshot (85)

**Comment by Rakesh9100** [comment]
Please do not create a PR until you have been assigned to an issue @Riyaa019

**Comment by Riyaa019** [comment]
Actually I forgot to create issue that's why I created after Creating the PR

**Pull request closed without merging**
