### PR TITLE
Added 404 Error Card

### LINKED ISSUE #1044: [Feature] Add 404 Error Card
### Description

404 Error Card.

### Screenshots

Screenshot 2024-06-17 200338

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
# Fixes Issue🛠️

Closes #1044 

# Description👨‍💻

I have added 404 Error Card.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-17 200338

### CODE REVIEW

**Comment by AbheetHacker4278** [comment]
@Rakesh9100 please check thsi PR

**Comment by Rakesh9100** [comment]
Which issue are you assigned to @AbheetHacker4278

**Comment by AbheetHacker4278** [comment]
> Which issue are you assigned to @AbheetHacker4278

issue number #1044

**Comment by AbheetHacker4278** [comment]
> Which issue are you assigned to @AbheetHacker4278 

@Rakesh9100 please assign this pr to me under gssoc24

**Comment by Rakesh9100** [comment]
PR is not being assigned, and don't create a PR until you have been assigned to an issue.

You should open an issue and wait to be assigned if you want to work and then create PR @AbheetHacker4278

**Comment by AbheetHacker4278** [comment]
> PR is not being assigned, and don't create a PR until you have been assigned to an issue.
> 
> You should open an issue and wait to be assigned if you want to work and then create PR @AbheetHacker4278 

Sorry for that , but now what i have to do , please tell , i haven't aware about guidlines

**Comment by AbheetHacker4278** [comment]
@Rakesh9100  bhai tell me something , what i have to do now

**Pull request merged**
