### PR TITLE
Added Stylist Scroll bar

### PR DESCRIPTION
**Pull request by divyansh2375**
# Fixes Issue🛠️

#111 

Closes #

# Description👨‍💻 

I have successfully added the stylist scroll bar 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by divyansh2375** [comment]
@Rakesh9100  I have successfully added the stylist scroll bar . Please review my PR

**Comment by divyansh2375** [comment]
also sorry @Rakesh9100 it was a bit late

**Comment by Rakesh9100** [comment]
Pls reduce the width of the scrollbar @divyansh2375 

Why other file changes are visible, only `style.css` should be changed. Do fix.

**Comment by divyansh2375** [comment]
> Pls reduce the width of the scrollbar @divyansh2375
> 
> Why other file changes are visible, only `style.css` should be changed. Do fix.

ok i will gonna fix it

**Comment by divyansh2375** [comment]
@Rakesh9100  i have lower the value of the scroll bar width

**Comment by divyansh2375** [comment]
> Pls reduce the width of the scrollbar @divyansh2375
> 
> Why other file changes are visible, only `style.css` should be changed. Do fix.

i changed only the styles.css but i don't know how to fix it ? can you tell me how can i solve it ?

**Comment by divyansh2375** [comment]
I got it know someone has contributed to that loaders folder but i have not pulled it in my system

**Comment by divyansh2375** [comment]
@Rakesh9100 you can review now i have successfully fixed it

**Comment by Rakesh9100** [comment]
Good, Merged!! ✨ @divyansh2375

**Pull request merged**
