### PR TITLE
Fixed hamburger menu in component category pages

### LINKED ISSUE #592: [Bug] Hamburger menu not working in component category pages
Fix the hamburger menu not coming up in every component category pages.

### PR DESCRIPTION
**Pull request by pb0126**
# Fixes Issue🛠️

Closes #592 

# Description👨‍💻 

The hamburger menu was not working on the component category page, after adding js files to the page it was working fine.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

The changes has been through tested by visiting one by one and using Chrome Developer tools

# Checklist✅ 

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [ ] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
As told in the PR you closed to make the space same between Contributors and Contact for every pages, pls see and do the changes in this PR only. Not needed to close the previous PR or this PR now.

image

**Comment by Rakesh9100** [comment]
### As told in the PR you closed to make the space same between Contributors and Contact for every pages, pls see and do the changes in this PR only. Not needed to close the previous PR or this PR now @pb0126 

image

**Comment by Rakesh9100** [comment]
Can I know why are you closing the PRs again and again, as you can make any changes in the same PR @pb0126

**Comment by pb0126** [comment]
I have discarded the commit as I have other issues fixed, they are also lining up with them.

**Comment by pb0126** [comment]
Also, I want to know where is the problem coming, I have fixed the margin between the components and contact

**Comment by Rakesh9100** [comment]
You can check all the components category pages and figure out the problem @pb0126

**Pull request closed without merging**
