### PR TITLE
Made Feedback Form-2 responsive

### LINKED ISSUE #1063: [Style] Make Feedback Form-2 responsive
### Description

Feedback-Form-2 is not responsive

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by abhirajadhikary06**
# Fixes Issue🛠️

Closes #1063 

# Description👨‍💻

- Made responsive across all devices.
- Changed the background color and added a gradient to the form card and added green border colors to placeholders.
- Added keyframe animation to the stars 

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)
- [x] Responsiveness (non-breaking change which improves UI/UX on different screen sizes)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
@abhirajadhikary06 

### Few things to note:
1. Always update the branch of your forked repo to avoid the conflicts, I have resolved this time.
2. Write `[x]` in the checkboxes of the PR description to check it.
3. Keep all your files with indent of 4 spaces always.

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Is any more changes required to get the file to a mergeable state.

**Comment by Rakesh9100** [comment]
Edit the PR description and check the checkboxes @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
> Edit the PR description and check the checkboxes @abhirajadhikary06

Done...

**Pull request merged**
