### PR TITLE
Added Jelly Button

### LINKED ISSUE #70: Adding Jelly Button to the website
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Right now there are only two types of buttons.
I can add a jelly button.

Please assign it to me under SWOC'24

### Screenshots

beautify button

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️
Closes #70

# Description👨‍💻 
Added Jelly Button

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
beautyjelly

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100  This is new Jelly Button Pr.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🥳 @GhoshAditi

**Comment by rishicds** [comment]
Well Done 😄

**Comment by GhoshAditi** [comment]
Thank you @rishicds @Rakesh9100

**Pull request merged**
