### PR TITLE
Added Gradient Stroke & Bounce Loader

### LINKED ISSUE #453: [Feature] Adding Gradient Stroke & Bounce Loader
### Description

I would like to add Gradient Stroke & Bounce Loader in Loaders section.
Please assign this issue to me.

https://github.com/Rakesh9100/Beautiify/assets/133951716/3fdf81d0-5aba-4810-b367-c51f23bfb14d

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by mansi1309**
# Fixes Issue🛠️

Closes #453 

# Description👨‍💻 
I added the Gradient Stroke & Bounce Loader in the Loaders section

# Type of change📄.

Adding a new feature in Loaders section.

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I check it on my laptop it works correctly ,you can check it.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
https://github.com/Rakesh9100/Beautiify/assets/133951716/45476ceb-d680-4204-a19f-08f1371bc2d5

### CODE REVIEW

**Comment by mansi1309** [comment]
@Rakesh9100 I added the new Loader and raise the PR. Please check it.

**Comment by mansi1309** [comment]
@Rakesh9100 While creating PR,by mistake merge commit clicked .Thats why it is shown in comment section

**Comment by Rakesh9100** [comment]
The files of Screensaver Background should not come in this PR, pls fix @mansi1309

**Comment by mansi1309** [comment]
@Rakesh9100 On clicking deploy preview it shows my addition in files and loader section

**Comment by mansi1309** [comment]
image

**Comment by Rakesh9100** [comment]
image

[Check this link](https://github.com/Rakesh9100/Beautiify/pull/468/files) as well @mansi1309

**Comment by mansi1309** [comment]
@Rakesh9100 please check ,I deleted the extra files

**Comment by mansi1309** [comment]
@Rakesh9100 If problem is arrises in this ,then can I close the pull request and again reopen or make new pull request for that iisue fixed .Can you suggest me what can I do ,because I does not have much knowledge of github.

**Comment by Rakesh9100** [comment]
WHy are you closing the PR, let me review when I am free and reply to your commented queries @mansi1309

**Comment by Rakesh9100** [comment]
Why are you closing the PR, let me review when I am free and reply to your commented queries @mansi1309 

No need to create a new PR!!

**Comment by mansi1309** [comment]
@Rakesh9100 okay you will check ,I created the new PR and there is no extra files in it.Please reply when you check

**Comment by Rakesh9100** [comment]
Pls attach the screenshot/demo of your loader in the PR description @mansi1309

**Comment by mansi1309** [comment]
beautify


Uploading Gradient Stroke & Bounce 🏀 loader - Google Chrome 2024-01-29 14-36-09.mp4…

**Comment by Rakesh9100** [comment]
Why are you adding the screenshot of loaders component page, attach the demo video of your loader page @mansi1309

**Comment by mansi1309** [comment]
https://github.com/Rakesh9100/Beautiify/assets/133951716/45476ceb-d680-4204-a19f-08f1371bc2d5

**Comment by Rakesh9100** [comment]
Merged 🎉 @mansi1309

**Comment by mansi1309** [comment]
Thankuu..

**Pull request merged**
