### PR TITLE
Enhanced the Home page

### LINKED ISSUE #449: [Style] Enhance the Home page
### What's the style idea?

We need to improve the overall look and feel of the Landing page of the website. I want to improve the hover effects of the cards made, the navbar, etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yuvraj960**
# Fixes Issue🛠️

Closes #449 

# Description👨‍💻 

Done changes in cards and the dark-light mode switch animation

# Type of change📄

- [] New feature (new cards and new animations)

# How this has been tested✅

Responsiveness checks done

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Hey @Yuvraj960 

Pls update your forked repo properly and then work on as all animations are removed in updated repo but not removed in your deploy preview.

Cards look is really not looking good, keep it as it was but try to give some good hover effects to cards as well as navbar.

Footer also does not looks good as per the background!!

**Comment by Rakesh9100** [comment]
Hey @Yuvraj960 

Pls update your forked repo properly and then work on as all animations are removed in updated repo but not removed in your deploy preview.

Cards look is really not looking good, keep it as it was but try to give some good hover effects to cards as well as navbar.

Footer also does not looks good as per the background, if no good design comes in mind then keep it as it was!!

**Comment by Yuvraj960** [comment]
@Rakesh9100, I update my repo time to time, but I can't understand which animations you are talking about. Please elaborate the specific animation as I can remove them manually again. 
And are you saying that I add your previous card design and update their hover effects?
I did like to take your honest feedback on my new card design that what do you don't like in it, if colors are wrong, I can change their gradient, if the size of the card is wrong, please let me know. Or any other fundamental design part missing as per you in the card, please give me a prompt, I will design the cards separately and present it to you before adding it to the repo.
For the navbar animation's part, I will surely think and implement some more hover effects also.
If you think footer is not looking good, I will surely revert it, but listen to my one suggestion, once the card design is final, I will implement the same color scheme in the footer as of the cards color scheme, which will make it look good from current version of the footer.

**Comment by Rakesh9100** [comment]
First of all, let's keep this PR and issue on hold as many issues opened by you are already on Standby mode in my another project `CalcDiverse`. So pls start completing them one by one @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 , I understand, that my work is not reflecting the way you want to see it in this project, but I assure you that when merging this PR, you will see the better version of myself and my work.

**Comment by Rakesh9100** [comment]
I can totally understand your dedication and effort, and so I am keeping this on hold for now so that your time should not waste and you can complete your remaining issues as SWOC end date is approaching @Yuvraj960

**Pull request closed without merging**
