### PR TITLE
Added Clock Loader

### LINKED ISSUE #191: Adding a Clock Loader
### Description

It is a loader designed like a clock, with rotating clock hands indicating the loading progress.
Please assign me this issue under IWOC

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Dhairya1Gupta**
# Fixes Issue🛠️

Closes #191

# Description👨‍💻 

# Type of change📄

- [] New feature (non-breaking change which adds functionality)
- Added a new Clock Loader

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
clockloader

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Warning:- This is your 3rd PR for this issue and this action comes under spamming of the PRs.

Suggestions:-
1. First, try to learn about resolving of the merge conflicts.
2. Always update your branch first before opening a PR.

@Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
> Warning:- This is your 3rd PR for this issue and this action comes under spamming of the PRs.
> 
> Suggestions:-
> 
> 1. First, try to learn about resolving of the merge conflicts.
> 2. Always update your branch first before opening a PR.
> 
> @Dhairya1Gupta

Sorry Sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged!! 🎉 @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
Merged!! 🎉 @Dhairya1Gupta

**Pull request merged**
