### PR TITLE
Added scroll to top button in Contact page

### LINKED ISSUE #1013: [Feature] Add scroll to top button in Contact page
### Description

There can be a back-to-top button present even in the contact page.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Yashop181**
# Fixes Issue🛠️

Closes #1013 

# Description👨‍💻

Added the back to top button in the contact page.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

### Before:
Before

### After:
After

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Please comment on the issue and get it assigned to you before creating a PR. Do not create a PR directly @Yashop181

**Comment by Rakesh9100** [comment]
Any update on this @Yashop181

**Comment by Yashop181** [comment]
Hi @Rakesh9100,

Thank you for the reminder about the contribution process. I apologize for not following the procedure of commenting and getting the issue assigned before creating the PR.

I have added the "Back to Top" button on the contact page , as it was not there before.

Please let me know if there are any further changes or updates required from my side. I appreciate your guidance and support.

**Comment by Yashop181** [comment]
### Description
The "Back to Top" button is currently missing on the contact page. Adding this button will improve user navigation by allowing users to easily return to the top of the page after scrolling down.

### Tasks
- [X] Add a "Back to Top" button on the contact page.
- [X] Style the button appropriately.
- [X] Ensure the button only appears when the user scrolls down.

### Screenshots

#### Before:
Before

#### After:
After

### Additional Information
I am not a part of GSSOC'24, IWOC'24, JWOC'24, or SWOC'24, but I am eager to contribute to this project. I have checked the boxes above to be able to submit this issue. Please let me know if there is any additional information or steps required from my side.

**Comment by Rakesh9100** [comment]
Comment in the issue #1013 that you want to work first to be assigned @Yashop181

**Comment by Yashop181** [comment]
@Rakesh9100 
I have commented on issue #1013 indicating that I would like to work on it.

**Pull request merged**
