### PR TITLE
Added Port ID Card

### LINKED ISSUE #730: [Feature] Add Port ID Card
### Description

It was  a mini ID card like structure , That have a About , Experience and contact section with Photograph

### Screenshots

Screenshot 2024-05-14 221316

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by codewithganeshhh**
# Fixes Issue🛠️

Closes #730 

# Description👨‍💻

I added Mini Portfolio card Name Port ID Card
It was simple made by HTML, CSS, JavaScript
It was added on Card Section 

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-20 170513

### CODE REVIEW

**Comment by codewithganeshhh** [comment]
@Rakesh9100 check the PR

**Comment by codewithganeshhh** [comment]
@Rakesh9100 check

**Comment by codewithganeshhh** [comment]
hello @Rakesh9100 add it

**Comment by codewithganeshhh** [comment]
hello sir @Rakesh9100 you changes some thing in code there is problem ?

**Comment by Rakesh9100** [comment]
There were conflicts that are resolved and some changes which I have done now @codewithganeshhh

**Comment by codewithganeshhh** [comment]
Thanks Mr @Rakesh9100

**Pull request merged**
