### PR TITLE
Added 3d cylindrically rotating text animation

### LINKED ISSUE #375: Addition of 3d rotating cylinder text animation
### Description

@Rakesh9100  i would like to add a 3d rotating cylindrical text animation . plz assign me this under jwoc'24.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #375 

# Description👨‍💻 
Added 3d cylindrically rotating text animation

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
Untitledbeauty

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100 plz check

**Comment by Rakesh9100** [comment]
Can you pls tell why changes are reflecting in the files of `Colour-Drop-Background` as well @GhoshAditi

**Comment by Rakesh9100** [comment]
[Check this] @GhoshAditi

**Comment by Rakesh9100** [comment]
[Check this](https://github.com/Rakesh9100/Beautiify/pull/382/files) @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 idk what happened. i didn't even touch them. can u plz say what should i do now?

**Comment by Rakesh9100** [comment]
Okay wait, I will fix them out @GhoshAditi

**Comment by GhoshAditi** [comment]
> Okay wait, I will fix them out @GhoshAditi

thank u very much :(

**Comment by Rakesh9100** [comment]
Merged 🥳 @GhoshAditi

**Pull request merged**
