### PR TITLE
Added glassmorphism search bar

### LINKED ISSUE #293: [Feature] New Glassmorphism search bar
### Description

I will create a new **Glassmorphism search bar** in search bar component.
I will use **HTML** and **CSS** for that.

Kindly assign this to me under **IWOC2024**.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
# Fixes Issue🛠️

#293 New Glassmorphism search bar

Closes #293 

# Description👨‍💻 

Added new **Glassmorphism search bar** in Search bar component.
It is made using HTML and CSS.

# How this has been tested✅

It is tested by me by running the website, no error found!

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/149922307/aa83acf5-11b0-4c2f-8a9a-c38c81e4a246

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls edit the PR description and check the checkboxes by writing x in the bracket with no extra spaces everytime @AbhineshJha

**Comment by Rakesh9100** [comment]
Pls edit the PR description and check the checkboxes by writing x in the bracket with no extra spaces everytime @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Done sir !

**Comment by Rakesh9100** [comment]
Merged 🥳 @Prince-kushwaha-2004

**Pull request merged**
