### PR TITLE
Contact Form component made responsive on small devices

### LINKED ISSUE #175: [Bug] Contact Form component not responsive on small devices
### Description

The 1st contact form in the forms section is not responsive below large screens, the content is set aside to one side when seeing the website in smaller screens.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by pb0126**
# Fixes Issue🛠️

Closes #175 

# Description👨‍💻 

The contact form in smaller screen was not responsive, the content is overflowing form the main container and the content inside was shrinking.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

All major checks are done by evaluating code several times and using Chrome Developer Tools for every screen

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Before: -
Screenshot 2024-01-13 093319

After:- 
image

image

### CODE REVIEW

**Comment by pb0126** [comment]
Hi @Rakesh9100 , the PR has been created, please go through the changes and merge it into the main branch, let me know if there are any changes. My apologies for the delay. I was stuck in some personal work.
Thanks

**Comment by Rakesh9100** [comment]
WHy UI for big screen is changed, fix it @pb0126

**Comment by pb0126** [comment]
HI, @Rakesh9100 Please verify the commit and merge it
Issues were fixed

**Comment by Rakesh9100** [comment]
Merged ✨ @pb0126

**Pull request merged**
