### PR TITLE
Enhanced the About Us page

### LINKED ISSUE #866: [Style] Enhance the About Us page
### What's the style idea?

I have seen a similar issue raised previously, but, I wanted to add a few more styling changes like:

- change in background colour
- Increasing font size
- Changing the font colour accordingly
- Adding a few more transitions to make the user experience better.

I have attached an example of my idea below.
Screenshot from 2024-06-02 14-19-00
This page would look like this in night mode.
image
This is just a simple demonstration of my idea. The final outlook would include more and better changes.
Please assign this issue to me under gssoc'24.
Thank you !

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by BhavyaV05**
# Fixes Issue🛠️

Closes #866

# Description👨‍💻

Have changed the background colour, added underlines and adjusted the image to make the overall page look neater.

# Type of Change📄

- [ ] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [ ] I am an Open Source contributor
- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot from 2024-07-08 16-50-26

Screenshot from 2024-07-08 16-50-16

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

### Why is it coming like this @BhavyaV05

**Comment by BhavyaV05** [comment]
There might have been a problem while merging with the latest code, as it appeared fine on my device(as the pictures have been attached). It appears so that the flex direction has been changed, however, I only made changes to the background colour and a few adjustments in the border widths. 
But I will also check from my side and get back to you on what might have cause the problem.

**Comment by BhavyaV05** [comment]
I have identified the problem, I believe line 53 in about.css "display:flex" is causing this problem. Since I had modified an older version of the code, it may have been edited later and caused the problem. Removing this line brings the preview back to normal.

**Comment by BhavyaV05** [comment]
I have removed that line, this problem has been fixed.

**Comment by Rakesh9100** [comment]
There are too many conflicts which I tried to resolve, but your UI got changed, pls check your branch if latest changes are pulled or not and then commit your new styling changes again in this same PR @BhavyaV05

**Comment by BhavyaV05** [comment]
yes, they have reflected, will do the necessary changes

**Comment by BhavyaV05** [comment]
Have made all the necessary changes, hope it looks fine now.

**Comment by BhavyaV05** [comment]
All the necessary changes have been made, please review them and let me know if there is anything else to fix

**Comment by BhavyaV05** [comment]
Thank you so much! This was a very nice experience, as it was my first experience with open-source projects. I had a great time working on Beautiify! :)

**Pull request merged**
