### PR TITLE
Added Apple Themed Dropdown

### LINKED ISSUE #870: [Feature] Add Apple Themed Dropdown
### Description

**Add Apple-inspired Dropdown Menu**

## Description
As part of the new feature development, I would like to add an Apple-inspired dropdown menu to the GitHub repository. The dropdown menu should have the following characteristics:

- Visually similar to the dropdown menus used in Apple's user interfaces
- Responsive and interactive, allowing users to easily navigate and select options
- Consistent with the overall design and branding of the project

## Expected Behavior
When the user clicks on the "Menu" button, a dropdown menu should appear, displaying a list of options. The dropdown menu should have the following features:

- Smooth transition when opening and closing the menu
- Hover effect on the menu options to indicate interactivity
- Ability to close the menu by clicking outside of it

## Assigned To
- [Vesper Akshay]

### Screenshots

Repo

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by VesperAkshay**
# Fixes Issue🛠️

Closes #870 

# Description👨‍💻 

The pull request adds a new feature for an apple theme dropdown menu. This will allow users to select a custom theme for the application interface.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

The new apple theme dropdown menu has been thoroughly tested in the development environment. It has been verified that the menu functions correctly, allowing users to select the desired theme and that the selected theme is properly applied to the user interface.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-06-02 210255

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the screenshots or video of your work @VesperAkshay

**Comment by VesperAkshay** [comment]
Screenshot of the Work Is Attached

**Comment by Rakesh9100** [comment]
Rename your folder to `Apple-Themed-Dropdown` and make the necessary changes by making the new commits in this same PR @VesperAkshay

**Comment by VesperAkshay** [comment]
Changes have been made

**Comment by VesperAkshay** [comment]
Changes made

**Pull request merged**
