### PR TITLE
Added Flower Effect Button

### LINKED ISSUE #1042: [Feature] Add Flower Effect Button
### Description

Adding a button when hoverd have a flower effects

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Fixes Issue🛠️

Closes #1042 

# Description👨‍💻

Added Flower Effect Button when the mouse hovers the flowers appears.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  can you please review soon so that i can work with your repo again

**Comment by Rakesh9100** [comment]
Pls add your button part in `buttons.html` in alphabetical order file by making the new commit in this same PR @Saipradyumnagoud

**Review by Saipradyumnagoud — COMMENTED** [review]
Changed the file name

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 I have changed the file name

**Review by Saipradyumnagoud — COMMENTED** [review]
done changes and placed in alphabetical order @Rakesh9100

**Pull request merged**
