### PR TITLE
Added Heroes Category and several Components

### LINKED ISSUE #925: [Feature] Add Heros Category and several Components
### Description

Create a new category specifically for hero sections in the repository. Design and implement several hero section, ensuring each component is customizable to fit different design requirements and brand aesthetics.
- Full-Screen Image hero 
- Video Background Hero
- Minimalist Hero
- Split-Screen Hero
- Carousel Hero
- Text-Only Hero
- even more

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
# Fixes Issue🛠️

Closes #925 

# Description👨‍💻

I have added hero category and below components to it.
1. text only
2. full screen image
3. full screen video
4. carousel
5. split screen
6. collage style

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

Screenshot 2024-06-15 094753

Screenshot 2024-06-15 094819

Screenshot 2024-06-15 094936

Screenshot 2024-06-15 094840

Screenshot 2024-06-15 094958

Screenshot 2024-06-15 094859

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
@Rakesh9100 Please kindly review this pr.

**Comment by Rakesh9100** [comment]
Pls change the Heros to `Heroes` wherever required and make the changes accordingly by making the new commits in this same PR @DharshiBalasubramaniyam

**Comment by Rakesh9100** [comment]
Pls change the Heros to `Heroes` wherever required and make the changes accordingly by making the new commits in this same PR!
Also, add `heroes.css` file @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
> Pls change the Heros to `Heroes` wherever required and make the changes accordingly by making the new commits in this same PR! Also, add `heroes.css` file @DharshiBalasubramaniyam

done! please review.

**Pull request merged**
