### PR TITLE
Added Hover Effects and Animations to all the Components Page

### LINKED ISSUE #393: [Style] Adding hover effects and animations to the components page cards
### What's the style idea?

We need to improve the hover effects in the Components page. They do not have nice hover effects. Also would like to add scroll animation on the cards. Please assign me under JWOC 2024. I am attaching the ScreenShot here.

Screenshot 2024-01-23 134317

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SohanRC**
# Fixes Issue🛠️

Closes #393 

# Description👨‍💻 

Added Hover Effects and Animations to all the Components Page. On Scrolling , we can see actual cards come as in the case of scrolling animations. This is done with pure CSS and Javascript.

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested in my Local System and it worked perfectly.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

### CODE REVIEW

**Comment by SohanRC** [comment]
@Rakesh9100 Please review my PR for Issue No = **#393**

**Comment by SohanRC** [comment]
@Rakesh9100 Please review this PR

**Comment by SohanRC** [comment]
@Rakesh9100  Hey !! Please Review This PR !! Please !!!

**Comment by Rakesh9100** [comment]
Pls do remove the reveal scroll animations @SohanRC

**Comment by SohanRC** [comment]
> Pls do remove the reveal scroll animations @SohanRC

OK i am removing wait

**Comment by SohanRC** [comment]
@Rakesh9100  Please Review it Now !! The Scroll Reveal Animation is removed

**Comment by SohanRC** [comment]
@Rakesh9100 Please review it Now !!

**Comment by Rakesh9100** [comment]
No extra changes to be done in the files, just keep your changes for easy review and quality PR @SohanRC 

Example: 
image

**Pull request closed without merging**
