### PR TITLE
Navigation bar in components

### LINKED ISSUE #9: Navigation on each component page
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As we click on components its opening in new tab and if we want to return to home again there is no option other than clicking the previous tab. So according to me we can add either the back button or the navigation bar itself to each component page to make website more interactive from user end.
I would like to contribute this under SWOC 2024 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/114792553/d2b0191c-6e50-4505-9dcd-ab1b4756698b

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by kanishka-parmar**
Closes #9 

# Description👨‍💻 

Navigation bar is added to all component page for ease in navigation.

# Type of change📄
- [] Navigation bar on each page.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2024-01-08 151905

Screenshot 2024-01-08 151931

### CODE REVIEW

**Comment by kanishka-parmar** [comment]
The navigation-bar.html I have given the code for future components and the previous navigation-bars.html is the component itself.
If you say I would delete if not required it is not used it's just the reference.
Ok I will fix the hamburger icon as well as the navbar position.
@Rakesh9100

**Comment by Rakesh9100** [comment]
Yes, I know navigation-bars.html is the component but not the navigation-bar.html, so delete that pls @kanishka-parmar 

I don't think its needed as for the future components, codes can be taken from any html file for reference.

**Comment by kanishka-parmar** [comment]
Ok i will delete that @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @kanishka-parmar

**Comment by Rakesh9100** [comment]
1. Pls resolve the conflicts.
2. See the landing page of real website and keep it the same in your case, don't do anything different not margin neither padding.
3. It should not overlap, keep the navbar z-index on top for all the pages @kanishka-parmar

**Comment by kanishka-parmar** [comment]
@Rakesh9100 
I have made the changes as suggested please check. I have attached screenshots of the responsive navigation bar also.


Screenshot 2024-01-09 005024
Screenshot 2024-01-09 005032

**Comment by Rakesh9100** [comment]
> 1. Pls resolve the conflicts.
> 2. See the landing page of real website and keep it the same in your case, don't do anything different not margin neither padding.
> 3. It should not overlap, keep the navbar z-index on top for all the pages
>    image
> 
> @kanishka-parmar

Pls see this @kanishka-parmar

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Yes i am working i didn't saw that.

**Comment by Rakesh9100** [comment]
And as for this, do make it cover the full page when clicking on the hamburger icon keeping the texts in center @kanishka-parmar 

image

**Comment by kanishka-parmar** [comment]
> > 1. Pls resolve the conflicts.
> > 2. See the landing page of real website and keep it the same in your case, don't do anything different not margin neither padding.
> > 3. It should not overlap, keep the navbar z-index on top for all the pages
> >    image
> > 
> > @kanishka-parmar
> 
> Pls see this and make changes accordingly @kanishka-parmar

So the nav bar should also scroll with the page or nav should be at its position and the page gets scrolled from behind it?

**Comment by Rakesh9100** [comment]
Navbar should be fixed/sticky and the page gets scrolled behind it @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> Navbar should be fixed/sticky and the page gets scrolled behind it @kanishka-parmar

ok sorry i got a little confused.
@Rakesh9100

**Comment by Rakesh9100** [comment]
No problem, go ahead and ask any queries you have @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> No problem, go ahead and ask any queries you have @kanishka-parmar

Yeah 👍

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Please check it once.

**Comment by Rakesh9100** [comment]
Spaces on top and left-right is coming again for the components navbar @kanishka-parmar Pls fix

**Comment by kanishka-parmar** [comment]
> Spaces on top and left-right is coming again for the components navbar @kanishka-parmar Pls fix
> 
> image

ok

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Done plz check.

**Comment by Rakesh9100** [comment]
Just one thing that on hovering the navbar menu of the components page, underline is coming in I guess pink color. Do change it to white for clear visibility @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> Just one thing that on hovering the navbar menu of the components page, underline is coming in I guess pink color. Do change it to white for clear visibility @kanishka-parmar

ok but it will change the home nav bar line also will it be fine ? @Rakesh9100

**Comment by Rakesh9100** [comment]
Home navbar line means? Can you clarify @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> Home navbar line means? Can you clarify @kanishka-parmar

No wait i thought home page also have same colour line but it's already white i will change the component page navbar menu hover line.

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Done.

**Comment by Rakesh9100** [comment]
Great work, Appreciated!! ✨

Congrats on getting your PR merged to this repo under SWOC S4 🥳🎉 @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> Great work, Appreciated!! ✨
> 
> Congrats on getting your PR merged to this repo under SWOC S4 🥳🎉 @kanishka-parmar

Thanks, it was a good experience!!!

**Pull request merged**
