### PR TITLE
update buttons.html

### PR DESCRIPTION
**Pull request by heypriyak**
# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
For which issue have you created this PR @heypriyak

**Comment by Rakesh9100** [comment]
Please do not create a PR until you have been assigned to an issue @heypriyak

**Comment by heypriyak** [comment]
please assign the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
You have not opened any issue, first create your issue properly to get assigned @heypriyak

**Pull request closed without merging**
