### PR TITLE
Added Newsletter Subscription Form

### LINKED ISSUE #406: [Feature] Adding Newsletter Subscription Form
### Description

The idea is to create a **Newsletter Subscription Form** for those who want a form pre-build newsletter subscription form.

If this issue is valid then assign me to work on this under **JWOC**

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by saurav2208**
# Fixes Issue🛠️

Closes #406 

# Description👨‍💻 
Added a newsletter subscription form under forms component

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# This has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/125905089/7a6a5dc7-12e1-440c-9695-d99ddbf1ec88

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Rename your folder to `Newsletter-Subscription-Form` and make the necessary changes @saurav2208

**Comment by saurav2208** [comment]
> Rename your folder to `Newsletter-Subscription-Form` and make the necessary changes @saurav2208

Updated

**Comment by Rakesh9100** [comment]
Correct the spelling of `Subscription` @saurav2208

**Comment by saurav2208** [comment]
> Correct the spelling of `Subscription` @saurav2208

Done

**Comment by Rakesh9100** [comment]
Merged 🎉 @saurav2208

**Pull request merged**
