### PR TITLE
Added 3D Popup Card

### LINKED ISSUE #282: [Feature] Adding 3D Popup Card
### Description

Hi
I want to add a set of 3D Popup Cards in which on hovering the cards, an image will popup a bit.

For better understanding, please see the attached video.

Please assign me this under IWOC2024.

https://github.com/Rakesh9100/Beautiify/assets/123951068/aaf0f1c7-44b6-4b8c-84f4-84e248466fd1

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Prithwi32**
# Fixes Issue🛠️

Closes #282 

# Description👨‍💻 

Added 3D-Popup animation to Beautify logo as example

Type of change📄
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I have tested the correct working of my form using live server of vscode.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/115262737/471b8243-ade2-4701-822f-067f63963e61

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Enclose this image in atleast a circle or any shape such that it looks like a card @Prithwi32

**Comment by Prithwi32** [comment]
> Are you working @Prithwi32

Yes sir, I will submit PR today

**Comment by Rakesh9100** [comment]
Make your changes commits in this PR only, no need to submit or create a new PR @Prithwi32

**Comment by Prithwi32** [comment]
> Make your changes commits in this PR only, no need to submit or create a new PR @Prithwi32

@Rakesh9100 Could you check out the changes now

**Comment by Rakesh9100** [comment]
Pls update the demo video in PR description @Prithwi32

**Comment by Prithwi32** [comment]
> Pls update the demo video in PR description @Prithwi32

https://github.com/Rakesh9100/Beautiify/assets/115262737/471b8243-ade2-4701-822f-067f63963e61

**Comment by Prithwi32** [comment]
> > Pls update the demo video in PR description @Prithwi32
> 
>  card-3D.mp4

@Rakesh9100 here is the demo

**Comment by Rakesh9100** [comment]
Why extra files changes of Payment Form is showing, do fix @Prithwi32 

[Check here](https://github.com/Rakesh9100/Beautiify/pull/481/files)

**Comment by Prithwi32** [comment]
@Rakesh9100 I made changes..please could you check out this now

**Comment by Rakesh9100** [comment]
Merged 🎉 @Prithwi32

**Pull request merged**
