### PR TITLE
3d Search bar addition 

### LINKED ISSUE #313: [Feature] Addition of 3d search bar
### Description

@Rakesh9100 i would like to add a 3d search bar . please assign it tome under swoc'24

### Screenshots

Untitled1

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #313 

# Description👨‍💻 
Added 3d search bar

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Untitle234d

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100 plz check

**Comment by Rakesh9100** [comment]
Can you pls tell why have you closed the previous PR @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100  I didn't commit it by making a separate branch as written in your Readme. After giving the pr I recalled that I have to do that. So this time I made a separate and then gave you a pr request.

**Comment by Rakesh9100** [comment]
It's a good habit to create PR in a new branch always but if you have created PR in main branch by mistake, then also no worries and no need to close the PR!! @GhoshAditi

**Comment by Rakesh9100** [comment]
Merged 🥳 @GhoshAditi

**Pull request merged**
