### PR TITLE
Added Torch Effect Login Form

### LINKED ISSUE #590: [Feature] Add Torch Effect Login Form
### Description

New animated **login form with torch effect**  in form section 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/125949765/bf330bec-18fb-49ea-ac57-65f30dbc6b51

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️  #590 

Closes #590 

# Description👨‍💻 

Added new torch effect login form 

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/125949765/bf330bec-18fb-49ea-ac57-65f30dbc6b51

### CODE REVIEW

**Comment by AftabMankapure** [comment]
@Rakesh9100  pls check this PR

**Comment by Rakesh9100** [comment]
You have just copied the code from a youtuber's website or his channel, you will not be assigned to any issues now @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  bro what about his pR 
i can change style then it is ok

**Comment by AftabMankapure** [comment]
umbar
@Rakesh9100  pls check this

**Comment by Rakesh9100** [comment]
Okay, make your new changes and push the commits in this same PR @AftabMankapure

**Comment by Rakesh9100** [comment]
Are you working @AftabMankapure

**Comment by Rakesh9100** [comment]
Merged 🎉 @AftabMankapure

**Pull request merged**
