### PR TITLE
Added 3d Rotating text

### LINKED ISSUE #120: Adding 3d rotating text animation
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i would like to add a rotating 3d text animation . please assign it to e under swoc'24.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #120 

# Description👨‍💻 
Added 3d Text Animation

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
beauty

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Rakesh9100 I have added the required text animation

**Comment by Rakesh9100** [comment]
Pls change your folder name to `3D-Rotating-Text-Animation` @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 i have used index.scss. the scss extension has transformed the code to index.css and index.css.map . so if i delete them the code will not run.

**Comment by GhoshAditi** [comment]
@Rakesh9100 is everything okay now?

**Comment by Rakesh9100** [comment]
Ohkk, I didn't observed that the `index.scss` file is used.

Nice, Merged!! 🥳 @GhoshAditi Keep Contributing!!

**Comment by GhoshAditi** [comment]
@Rakesh9100 Thank you

**Comment by rishicds** [comment]
Nice feature @GhoshAditi 👍🏼

**Pull request merged**
