### PR TITLE
Added Icons to navigation bar

### LINKED ISSUE #412: Adding icon on nav bar
### What's the style idea?

We need to add icon to nav bar on every page as it's already on home page. In home page, home icon is beside home and components icon is beside components button etc.  And same i have to add to every page.
Screenshot (8)
Screenshot (9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Vishalkr10**
# Fixes Issue🛠️

Closes #412

# Description👨‍💻 

Added icons to nav bar.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on local environment.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (10)
Screenshot (11)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Please include the Font Awesome icon that appears on the homepage in the About menu on every page @Vishalkr10

**Comment by Rakesh9100** [comment]
image

The icon is added to About menu item in the home page, so include that in every component page as well @Vishalkr10

**Comment by Vishalkr10** [comment]
Okay got it

**Comment by Vishalkr10** [comment]
@Rakesh9100 please review

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @Vishalkr10

**Pull request merged**
