### PR TITLE
Contact Page added

### PR DESCRIPTION
**Pull request by vishal0316**

### CODE REVIEW

**Comment by vishal0316** [comment]
image

**Comment by Rakesh9100** [comment]
Have you created this PR under SWOC? @vishal0316

**Comment by vishal0316** [comment]
> Owner

yes

**Comment by Rakesh9100** [comment]
SWOC contribution starts from 1st Jan 2024 @vishal0316 
So closing this PR for now! Good Luck!!

**Comment by vishal0316** [comment]
> SWOC contribution starts from 1st Jan 2024 @vishal0316 
> So closing this PR for now! Good Luck!!

So is this countable or not?

**Comment by Rakesh9100** [comment]
No
Issue will get assigned from 1st jan 2024 and then only you can create your PR @vishal0316

**Pull request closed without merging**
