### PR TITLE
Displayed the name of contributor on hovering

### LINKED ISSUE #1102: [Feature] Display the name of contributor on hovering
### Description

In the contributor page, currently only the images of contributors are being displayed.
It would look better if the contributor's GitHub username is also being displayed on hovering above his/her image.

### Screenshots

This is the current contributors page:
ss1

This is with a sample case:
(I wont change other components like background image/colour, below is just an example for displaying name additionally on hovering)
ss2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by NidhiTornekar**
# Fixes Issue🛠️

Closes #1102 

# Description👨‍💻

Modified contributor.js and contributor.css to fetch contributor's GitHub username and display it on hovering above the contributor's image in the "Contributors" page.

# Type of Change📄

- [X] New feature (non-breaking change which adds functionality)

# Checklist✅

- [X] I am an Open Source contributor
- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

ss3

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Please fetch and display the full name instead of the GitHub username. If the full name is not available on the profile, display the username instead @NidhiTornekar

**Comment by Rakesh9100** [comment]
It is not working properly for all the profiles, check the deploy preview @NidhiTornekar

**Comment by Rakesh9100** [comment]
Any update on this @NidhiTornekar

**Comment by NidhiTornekar** [comment]
It is exceeding the github rate limit of 60 requests per hour...Hence am unable o fetch for all the contributors

**Comment by Rakesh9100** [comment]
Yes, so in this case we can use Google app Script API that has no limit @NidhiTornekar

**Pull request closed without merging**
