### PR TITLE
Enhanced the About page

### LINKED ISSUE #766: [Style] Enhance the About page
### What's the style idea?

In my opinion. the about page is not styled properly. It looks like a plain text with black background. If given a chance I will try to enhance its appearance to the best of my ability

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by syannam-12**
# Fixes Issue🛠️

Closes #766 

# Description👨‍💻

Updated the background of the about page from a dark background to a vibrant background that aligns with the theme of Beautiify website.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

beautiify

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Mention the issue number for this PR.
Also, attach the screenshots of your work @syannam-12

**Comment by syannam-12** [comment]
issue number #766 
beautiify

**Comment by Rakesh9100** [comment]
Edit and fill all the details in the PR description above properly @syannam-12

**Comment by syannam-12** [comment]
I have filled the details properly. I hope you let me know in detail if
there's still any problem.

**Comment by syannam-12** [comment]
@Rakesh9100 It's been a long time since I provided my PR. Please review it and let me know if there's still any modifications to be done. I hope you do it as soon as possible

**Pull request merged**
