### PR TITLE
Added Dynamic Gradient Background

### LINKED ISSUE #98: Add Dynamic Gradient Background
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Implement a visually appealing background enhancement - a seamless, moving gradient effect. This feature aims to introduce a dynamic touch to website backgrounds without requiring customization. The gradient will smoothly transition across the background, contributing to an engaging user experience.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by DaSeeker67**
Closes #98 

# Description👨‍💻 

added new folder "Dynamic-Gradient-Background" having two files index.html and style.css

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [+] My code follows the style guidelines of this project
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have added demonstration in the form of GIF/video file
- [+] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Do add your component in main `backgrounds.html` file @DaSeeker67

**Comment by Rakesh9100** [comment]
Pls add your component in main `backgrounds.html` file @DaSeeker67

**Comment by DaSeeker67** [comment]
> Pls add your component in main `backgrounds.html` file @DaSeeker67

updated the main 'backgrounds.html' file @Rakesh9100  please add the swoc 4 labels and merge

**Comment by Rakesh9100** [comment]
Do resolve the conflicts @DaSeeker67

**Comment by Rakesh9100** [comment]
Don't do any other changes in `backgrounds.html` file excepot adding your background section @DaSeeker67 Do fix pls

**Comment by DaSeeker67** [comment]
> Don't do any other changes in `backgrounds.html` file excepot adding your background section @DaSeeker67 Do fix pls

updated main index.js ,

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @DaSeeker67

**Pull request merged**
