### PR TITLE
Added Swag Shipment Form

### LINKED ISSUE #1393: [Feature] Add Swag Shipment Form
### Description

Add a new form named `Swag Shipment Form` to the Form section. The form can be used during the shipment of any swags for the receiver to fill their details like their Name, Phone number with country code, Email and then the Main address. @Rakesh9100 want to work on to add this new feature.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by abhirajadhikary06**
# Fixes Issue🛠️

Closes #1393 

# Description👨‍💻

Built a swag shipment form with all kinds of necessary placeholders. A screenshot of the same has been attached.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Made a PR please check.

**Comment by Rakesh9100** [comment]
Fix the previous PR commits shown in this PR commits tree, don't create a new PR, fix the issue in this one itself.
Also add your form in `forms.html` file @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
> Fix the previous PR commits shown in this PR commits tree, don't create a new PR, fix the issue in this one itself. Also add your form in `forms.html` file @abhirajadhikary06

I have made different branch to make my work clean and segregated. 
I will be adding this `Swag Shipment Form` to `forms.html`. Other than this if you could tell me what I exactly need to do it would be clear for me to understand and work on it asap.

**Comment by Rakesh9100** [comment]
Please enhance the UI properly, visibility is too less @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Enhanced the UI of the form

- Added a dark color to the navbar
- Add a card background behind the placeholders
- Increased the fonts used in the body of the form
- When clicked on the placeholder a dark green color is used to focus the particular placeholder

**Comment by Rakesh9100** [comment]
Check two other forms files are deleted, don't be in hurry and make quality PR else your PRs will not be merged @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Yes I have seen those form files but they were on my "address-form" branch so I have removed those.
I'm sorry for deleting those files.

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 thank you for merging this PR

**Pull request merged**
