### PR TITLE
Dark/Light mode button placed in proper position

### LINKED ISSUE #536: [Bug] Dark/Light mode button is not placed proper position
### Description

Dark/Light mode button is not placed proper position 
We can add it in navbar after the contact 

### Screenshots

Current 

Gn

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Fixes Issue🛠️  #536 

Closes #536 

# Description👨‍💻 

Toggle button position is changed 
# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
nav

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
nav

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Fix the button position in every pages, it is only fixed in home page @AftabMankapure

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Rakesh9100** [comment]
Fix the button position on every components cards page as well.

image

And why the menu items went little up, fix this @AftabMankapure

**Comment by Rakesh9100** [comment]
Fix the 2nd mentioned change in the above comment @AftabMankapure

**Comment by AftabMankapure** [comment]
Screenshot 2024-02-18 130520
 
menu is not going upper when we hover on it it match the size of toggle button 
if we make same with of menu to toggle then after hover to menu it will go outside of nav bar 

Screenshot 2024-02-18 130520

**Comment by Rakesh9100** [comment]
Navbar should not be altered in any case as it is now in the website, you can decrease the size of the button slightly and make sure not to increase the height of the navbar @AftabMankapure

**Comment by Rakesh9100** [comment]
I have fixed and merged ✨ @AftabMankapure

**Pull request merged**
