### PR TITLE
Added Text To Voice Converter Form & QR Code Generator Form

### LINKED ISSUE #584: [Feature] Add Text To Voice Form & QR Code Generator Form
### What would you like to share?

Want to add these forms:
1. Text To Voice Converter form - Contains a text area to write texts and later converts it into voice.
2. QR Code generator form - Just enter any URL of a website and get a qr code.
3. Modal/ Popup login form - Create a form that pops up in a modal window when a button is clicked.

### Additional information

Please assign me under JWOC 2024

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by ratnojitsaha**
Text To Voice Converter form - Contains a text area to write texts and later converts it into voice .
QR Code generator form - Just enter any url of a website and get a QR code .

# Fixes Issue🛠️

Closes #584 

JWOC 2024

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (544)
Screenshot (545)
Screenshot (546)
Screenshot (547)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You have copied both the forms code of a youtuber which is not acceptable and you will be banned from open source programs if done again @ratnojitsaha

**Comment by ratnojitsaha** [comment]
@Rakesh9100 Yes I did, thinking that 24th mid night 12am is the ending of the phase 2.And I am sorry for it. 
If you give me another chance I will make a better one. And will submit it to you by tonight

**Comment by Rakesh9100** [comment]
Okay proceed and push your new changes in this same PR @ratnojitsaha

**Comment by ratnojitsaha** [comment]
@Rakesh9100  please check, I deleted the newly added pull request, as after editing I could not see no notification for compare and merge which should be obvious, that time my mind didn't work I just deleted the whole file from my laptop and re cloned the beautify and worked on it.

**Comment by ratnojitsaha** [comment]
Moreover for clearance,
I have completely changed the QR code generator and added the size of qrs and download option too, 
And the text to voice I change some basic things, also I was trying to give the Google voices for Indian languages which I failed and kept the prior voices but Hindi is there as Indian voice

**Pull request closed without merging**
