### PR TITLE
Added Navigator Breadcrumb

### LINKED ISSUE #287: [Feature] Navigator Breadcumb
### Description

To add a navigator breadcumb which naviates after clicking on links

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/d418b7ff-20e6-47e2-a4f0-743fe16d6c33

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #287 

# Description👨‍💻 

Added Navigator Breadcrumb : A Navigator which navigates after clicking on respective link .! 
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/142514166/0fdabd64-840d-4b38-a8c1-0f4e82fb6193

### CODE REVIEW

**Comment by AbhineshJha** [comment]
I don't added the header because it looks better without header, but if you wanna add then lemme know..! @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls edit the PR description and check the checkboxes by writing x in the bracket with no extra spaces everytime @AbhineshJha

**Comment by AbhineshJha** [comment]
Done @Rakesh9100 👍

**Comment by Rakesh9100** [comment]
Good, Merged 🥳 @AbhineshJha

**Pull request merged**
