### PR TITLE
Fixed overlapping of scroll to top button with chatbot

### LINKED ISSUE #697: [Bug] Fix overlapping of scroll to top button with chatbot
### What would you like to share?

**Issue:**
The scroll-to-top button on the page is positioned unusually close to the chatbot open button, causing a potential usability concern.

**Details:**
Upon scrolling down the page, the scroll-to-top button becomes visible. However, its proximity to the chatbot open button is causing confusion for users. This close placement may lead to accidental clicks or hinder the ease of accessing the chatbot functionality.

**Expected Behavior:**
The scroll-to-top button should be positioned in a location that prevents overlap or confusion with other interactive elements, such as the chatbot open button. Users should be able to easily identify and interact with both buttons without interference.

**Steps to Reproduce:**

Scroll down the page to reveal the scroll-to-top button.
Observe its placement in relation to the chatbot open button

### Additional information

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SahilThakur02**
# Fixes Issue🛠️

Closes #697 

# Description👨‍💻 

Fixed the overlapping issue where the scroll-to-top button was obstructing the chatbot. Adjusted positioning to ensure both elements function without interference.
This commit resolves the overlapping issue where the scroll-to-top button was obstructing the chatbot. Adjusted the positioning to ensure that both elements are functional and do not interfere with each other.

# Type of change📄

- [X] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Ran the new compiled code with edited style.css file, worked perfectly!

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
project

### CODE REVIEW

**Comment by SahilThakur02** [comment]
> Pls place it below the chatbot icon, and not above that @SahilThakur02 

I will do it!

**Comment by SahilThakur02** [comment]
@Rakesh9100 I tried replacing its position below the chatbot icon, however it looks too packed there, do you still want it there?
second

**Comment by saurabhsingh720** [comment]
@SahilThakur02 
Try to create some gap between the two icons.

**Comment by SahilThakur02** [comment]
@saurabhsingh720 
this chatbox is added with an external script I think, cannot find its CSS where I can re-adjust its location. Can you please guide?
I could manage to move the scroll-to-top button wherever I want, but finding difficulty in moving the chatbox icon. Some guidance, tips will be appreciated! I'll also try to figure it out myself meanwhile.

**Pull request merged**
