### PR TITLE
Added 3D Breadcrumb

### LINKED ISSUE #143: Addition of 3D Breadcrumb
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i would like to add a new 3d breadcrumb.
please assign it to me under swoc'24

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by GhoshAditi**
# Fixes Issue🛠️

Closes #143 

# Description👨‍💻 
Added 3D breadcrumb

# Type of change📄
- [X] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
bread

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Hey @GhoshAditi 

Pls don't work on issues assigned to some other contributor!!

**Comment by GhoshAditi** [comment]
@Rakesh9100  u assigned this to me

**Comment by Rakesh9100** [comment]
But how the UI and design is same as mentioned in issue #152 @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100  i said i am gonna add a 3d breadcrumb. the issue number 143. so how did it became some other contributor's issue?

**Comment by GhoshAditi** [comment]
@Rakesh9100 how would i know that ? we are friends so we often discuss on what type of issue to create  and what to contribute .so  this was a clash i guess.

**Comment by GhoshAditi** [comment]
@Rakesh9100 sorry for the inconvenience faced.

**Comment by Rakesh9100** [comment]
@GhoshAditi Okay but pls take care that this clash should not happen from the next time!!

**Comment by GhoshAditi** [comment]
@Rakesh9100 yes. thank you and sorry at the same time.

**Comment by Rakesh9100** [comment]
Why so many file changes are shown, pls do fix @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 can u plz say once again what to change? i didnot understand actually what u said.

**Comment by Rakesh9100** [comment]
You Color-Drop-Background files are also shown as commits on this PR, [Check this](https://github.com/Rakesh9100/Beautiify/pull/153/files) @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 is it okay now?
can you please check.

**Comment by Rakesh9100** [comment]
No, its not fixed. You have deleted the other files which should not be done @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 shall i create another pull request?

**Comment by Rakesh9100** [comment]
Before creating another PR, update your branch properly so that these conflicts don't occur OR you can pull the latest changes @GhoshAditi

**Pull request closed without merging**
