### PR TITLE
Added Feedback form

### LINKED ISSUE #224: [Feature] Adding a feedback form under Forms section
### Description

It will be used to take feedback from Users  who are consuming their services.
Please assign me this issue under IWOC2024 @Rakesh9100 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by sksinha2410**
# Fixes Issue🛠️

Adding a feedback form under Forms section #224

Closes #224 

# Description👨‍💻 

I have included Feedback Form to project so that it can be used to collect feedbacks fr0m users websites.

# Type of change📄

- [✅] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested the correct working of my form using live server of vscode.

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of jpeg file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot 2024-01-16 at 2 21 40 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls edit the PR description properly as per the template @sksinha2410

**Comment by sksinha2410** [comment]
updated  description as per template

**Comment by Rakesh9100** [comment]
Use some new and different background @sksinha2410

**Comment by sksinha2410** [comment]
modified as per instruction.

Screenshot 2024-01-16 at 8 03 29 PM

**Comment by Rakesh9100** [comment]
Keep your form in your component folder and not in main assets folder @sksinha2410

**Comment by sksinha2410** [comment]
My Form is in components/Forms/Feedback_form , i guess you haven't noticed that or maybe have some doubt

**Comment by Rakesh9100** [comment]
Sorry, I mean to say your background image to keep in your folder @sksinha2410

**Comment by sksinha2410** [comment]
modified as per instruction

**Comment by Rakesh9100** [comment]
Rename your folder to `Feedback-Form` and bg4.jpeg to `background.jpeg` and make the necessary changes wherever required @sksinha2410

**Comment by sksinha2410** [comment]
Updated

**Comment by Rakesh9100** [comment]
Good job, Merged!! 🎉😀 @sksinha2410

**Pull request merged**
