### PR TITLE
Polaroid Like Photo Carousel

### LINKED ISSUE #255: [Feature] Polaroid Like Photo Carousel
### Description

It animates over a stack like structure

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/285682a7-df64-459c-96fd-0b57c4aec3ac

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #255 

# Description👨‍💻 

Added a Polaroid-Like-Photo-Carousel which goes down the picture over a picture >>

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/142514166/958a757e-9f86-41d5-89b0-85877dd17df7

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Merged 🎉 @AbhineshJha

**Comment by AbhineshJha** [comment]
thankyou @Rakesh9100 !! but is it a easy labelled program ?

**Comment by Rakesh9100** [comment]
What do you think of for this simple component code @AbhineshJha

**Comment by AbhineshJha** [comment]
okey ! as your wish

**Comment by Rakesh9100** [comment]
It's not about making a wish. I am always and already assigning labels based on the quality of work, ensuring that individuals receive a label equal to or greater than what they truly deserve. You must have got to know this till now as many of your PRs are merged being an active contributor!! @AbhineshJha

**Comment by AbhineshJha** [comment]
yeah yeah ! sorry for that.. If you found something wrong form my word , i am really sorry..!

**Comment by Rakesh9100** [comment]
It's not about making a wish. I am always and already assigning labels based on the quality of work, ensuring that individuals receive a label equal to or greater than what they truly deserve. You must have got to know till now as many of your PRs are merged to my projects being an active contributor!! @AbhineshJha

**Comment by AbhineshJha** [comment]
yessss !! i know sorry for my mistake.. @Rakesh9100

**Pull request merged**
