### PR TITLE
Added hover effects and animations to the components page cards

### LINKED ISSUE #393: [Style] Adding hover effects and animations to the components page cards
### What's the style idea?

We need to improve the hover effects in the Components page. They do not have nice hover effects. Also would like to add scroll animation on the cards. Please assign me under JWOC 2024. I am attaching the ScreenShot here.

Screenshot 2024-01-23 134317

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SohanRC**
# Fixes Issue🛠️

Closes #393 

# Description👨‍💻 

Adding hover effects and animations to the components page cards

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested in Local System and worked perfectly !

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

### CODE REVIEW

**Comment by SohanRC** [comment]
@Rakesh9100 Resolved all conflicts ! Please review this now !!

**Comment by SohanRC** [comment]
@Rakesh9100 Please check now !!

**Comment by SohanRC** [comment]
@Rakesh9100 Please check this !

**Comment by Rakesh9100** [comment]
Merged ✨ @SohanRC

**Pull request merged**
