### PR TITLE
Added Hover Effects to Contact Form

### LINKED ISSUE #56: Enhancing UI and Centering the Contact Form
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- the Contact Form was not exactly in center of the page.
- now have adjusted this for smaller screens as well.
- added shadows in the Contact Form to Improve the UI for this page

*Screenshots and screen recordings are provided below*

### Screenshots

*Screenshots*

**before**

before ss

**after**

after ss

*Screen Recording (After)*

https://github.com/Rakesh9100/Beautiify/assets/98605616/8a9ce87a-995a-4eb2-99e6-158c34ba0598

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by shivamm-verma**
# Fixes Issue🛠️ Closes #56 

# Description👨‍💻 

Added Hover Effects in Contact Form and Background-image of the page

# Type of change📄

- [] New feature (Adds Hover Effects)

# How this has been tested✅

- go to Contact from Home Page.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

*Shadows in card, hover effect in bg-image*

https://github.com/Rakesh9100/Beautiify/assets/98605616/2aeda3c3-b9e8-49f1-809d-97528cbee413

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When hovered to the contact form, the background is getting dull due to too much shadow effect. Pls reduce it accordingly @shivamm-verma

**Comment by shivamm-verma** [comment]
Okay i added that Feature (hover effect on background image) as well. Removing it...

**Comment by shivamm-verma** [comment]
confirm me to revert that Bg-Image-hover-effect commit.

**Comment by Rakesh9100** [comment]
What are you trying to ask? Just make new changes and push and make the commit to this PR, that's it @shivamm-verma

**Comment by Rakesh9100** [comment]
Merged!! 🎉 @shivamm-verma

**Pull request merged**
