### PR TITLE
Added Color Cube Card

### LINKED ISSUE #969: [Feature] Add Cube Color Card
### Description

I want to add the attractive cube card when we hover on it will show the different colors 

### Screenshots

image

[8e66824f-e4a8-4757-bdbb-9689e1a099c1.webm](https://github.com/Rakesh9100/Beautiify/assets/119167105/58d6f180-bea8-4273-93ef-d79784807d32)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SaiyamTuteja**
# Fixes Issue🛠️

Closes #969 

# Description👨‍💻

I have created the new folder named as cube-color-card and in this folder I created two files as index.html and style.css and also changes some code in the assets page.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

image

image

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Component looks good, but it don't resemble any type of card @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
Many of the website will use this type of card or a hover effect card for increasing the visitors time on website ( or engaging in cube ) if  you like that its something deferent then you can leave it  or if you feel its appropriate then you can merge otherwise no issues

**Comment by Rakesh9100** [comment]
If this is used to increase the visitors time on the website, then will it come under the Loaders category? @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
Yes we can put this into the loader section of you feel it's ok the I can change it and then put it into the loader section

**Pull request closed without merging**
