### PR TITLE
Scroll To Top Button Ready

### LINKED ISSUE #36: [SWOC'24] Back to top button
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- I would like to create a back to top arrow button for the website.
- Responsive for any type of devices.
- Hovering with neon light effect.
- Best user experience with smooth scroll functioning.
- Helpful for the user to reach out to the top of the website in one click.

### Screenshots

image

- No back to top button.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Fixes Issue🛠️

Closes #36 

# Description👨‍💻 

- Adding a scroll to top button.
- Styling the button using css and adding a loader around the arrow.
- Adding animation on hovering on the arrow button.
- Responsive for small devices too.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

By watching the ss and new deploy website 😎 on netlify.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please review this pr and requested to merge this pr under SWOC'24

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please again review this pr. Conflicts are resolved!

**Comment by Rakesh9100** [comment]
Why some extra css changes are visible in `style.css file. Do fix @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
> Why some extra css changes are visible in `style.css` file. Do fix @Avdhesh-Varshney

@Rakesh9100 i don't know why this code is comes here. As recently, i have just resolved the conflicts. I think, this code may already in the main branch.

**Comment by Rakesh9100** [comment]
> > Why some extra css changes are visible in `style.css` file. Do fix @Avdhesh-Varshney
> 
> @Rakesh9100 i don't know why this code is comes here. As recently, i have just resolved the conflicts. I think, this code may already in the main branch.

The previous code gets stored and new changes gets staged when you are pulling the changes and so creates some issue.

Good, Merged!! 🥳 @Avdhesh-Varshney

**Pull request merged**
