### PR TITLE
 Added new Navbar to navbar section (#854 fixed)

### PR DESCRIPTION
**Pull request by akshadgujarkar**
#854 
According to issue I created a simplistic navbar  with hover animations.

### CODE REVIEW

**Comment by saurabhsingh720** [comment]
@akshadgujarkar 
Can u give a preview of changes u have made.

**Comment by akshadgujarkar** [comment]
sure 


https://github.com/Rakesh9100/Beautiify/assets/142382794/3a235040-322d-4b49-a31b-76ee783c30df

**Comment by Praneeth-2602** [comment]
The issue was not even assigned. I raised this issue...

**Comment by saurabhsingh720** [comment]
@akshadgujarkar not needed

**Pull request closed without merging**
