### PR TITLE
Fixed redirection problem on about page

### LINKED ISSUE #458: [Bug] Redirection problem on about page
### Description

when we are on the about page and we click the about option again on the nav bar the whole page reloads this can be the major security issue as well becoz the content in about section is static so no need of refresh this page again nd again just like when we click HOME  page in 2nd or third time it is not refreshing .

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133164017/782907da-cdb7-4ea8-98b7-882597df48df

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by SohanRC**
# Fixes Issue🛠️

Closes #458 

# Description👨‍💻 

Previously when we were on the about page and we click the about option again on the nav bar, the whole page reloaded. It is resolved now !

# Type of change📄

- [X] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Tested on local system and it worked  fine !

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the demo video in the PR description @SohanRC

**Comment by SohanRC** [comment]
> Pls attach the demo video in the PR description @SohanRC


https://github.com/Rakesh9100/Beautiify/assets/124901633/0073c482-5c9d-4842-a04b-f023cf8d623a

**Comment by SohanRC** [comment]
@Rakesh9100 Please review now !

**Comment by Rakesh9100** [comment]
Merged 🎉 @SohanRC

**Pull request merged**
