### PR TITLE
Created Mouse-On-Wheel Loader

### LINKED ISSUE #233: [Feature] Mouse On Wheel Loader
### Description

I want to add a " Mouse On Wheel " Loader in the Loaders Section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/18a61a66-8e44-4c71-a097-692b12df8460

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
# Fixes Issue🛠️

Closes #233 

# Description👨‍💻 

 Created a " Mouse On Wheel " Loader in the Loaders Section

# Type of change📄
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on local system and it worked as expected

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://github.com/Rakesh9100/Beautiify/assets/140608790/db89ac4c-4779-4a28-a029-beb1309836c0

image

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 I'll do it please don't close

**Comment by Rakesh9100** [comment]
Okay, opening but complete it asap @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Done

**Comment by Rakesh9100** [comment]
Pls rename your folder to `Mouse-On-Wheel-Loader` and make the necessary changes @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Done sir, I hope it resolves all the conflicts now.

**Comment by Rakesh9100** [comment]
Good, Merged 🥳 @JiyaGupta-cs

**Pull request closed without merging**
