### PR TITLE
Added Animated SignIn Form

### LINKED ISSUE #459: [Feature] Animated SignIn Form
### Description

Wanna add a animated sign in form which has some animated background.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #459 

# Description👨‍💻 

Added animated signin form.
 
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by AbhineshJha** [comment]
Have a revieweee @Rakesh9100

**Comment by Rakesh9100** [comment]
This is a SignIn and not SignUp form, so make the folder renames and all the changes accordingly @AbhineshJha

**Comment by AbhineshJha** [comment]
done @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged ✨ @AbhineshJha

**Pull request merged**
