### PR TITLE
Added Customer Complaint Form

### LINKED ISSUE #869: [Feature] Add Customer Complaint Form
### Description

Allows customers to submit complaints with details of the issue and desired resolution.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Nayanika1402**
# Fixes Issue🛠️

Closes #869 

# Description👨‍💻

Customer Complaint Form Added.

# Type of Change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas

# Screenshots/GIF📷

Screenshot 2024-06-16 203747

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Why the files of Hotel Reservation Form is showing, pls fix by making the commits in this same PR @Nayanika1402

**Comment by Nayanika1402** [comment]
@Rakesh9100 Sorry for the issue.Now you can merge this pr.

**Comment by Rakesh9100** [comment]
image

Form is not getting scrolled to the starting top, pls fix @Nayanika1402

**Comment by Nayanika1402** [comment]
@Rakesh9100 Problem solved

**Pull request merged**
