### PR TITLE
Enhanced the theme toggle icon

### LINKED ISSUE #913: [Style] Enhance the theme toggle icon
### What's the style idea?

Current toggle icon look bit unstyled - 

Screenshot 2024-06-08 105334

I will make it more attractive like below - 

Dark Mode -
Screenshot 2024-06-08 111924

Light Mode -
Screenshot 2024-06-08 111804

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by PratikMane0112**
# Fixes Issue🛠️

Closes #913 

# Description👨‍💻

I have added an appropriate theme icons.
Added images of sun and moon in index.html & change style as per requirement in style.css.

# Type of Change📄

- [x] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [x] I am an Open Source contributor
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project

# Screenshots/GIF📷

### Desktop view - 
Screenshot 2024-06-22 230520

Screenshot 2024-06-22 230512

### Mobile view -
Screenshot 2024-06-22 230544

Screenshot 2024-06-22 230537

### CODE REVIEW

**Comment by Rakesh9100** [comment]
In home page, it is fine but on About, Contributors, Contact and all the category pages such as Accordions, Backgrounds, etc. previous icon and current icon is overlapping. Pls fix for all those pages as well properly @PratikMane0112

**Comment by PratikMane0112** [comment]
So, sorry for inconvenience, I will fix it ASAP !!!

**Comment by Rakesh9100** [comment]
Make the new commits in this same PR, don't create a new PR @PratikMane0112

**Comment by PratikMane0112** [comment]
> Make the new commits in this same PR, don't create a new PR @PratikMane0112

Done @Rakesh9100

**Comment by PratikMane0112** [comment]
Sir, Plz add gssoc label !!!!!

**Comment by Rakesh9100** [comment]
Level 2 is already added @PratikMane0112

**Comment by PratikMane0112** [comment]
No, not about level but by mistake enhancement label was added instead of
gssoc. Now it is fine.

**Pull request merged**
