### PR TITLE
Added Animated Breadcrumb

### LINKED ISSUE #152: Add animated Breadcrumb
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I wish to add an animated breadcrumb.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### LINKED ISSUE #286: [Feature] Animated Breadcrumbs
### Description

To add a animated breadcrum which slides like a slider..

### Screenshots

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by AbhineshJha**
# Fixes Issue🛠️

Closes #286 

# Description👨‍💻 

Added Animated breadcrumb which slides like a slider
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflicts pls @AbhineshJha

**Comment by AbhineshJha** [comment]
done @Rakesh9100

**Comment by Rakesh9100** [comment]
Make it responsive for small devices @AbhineshJha

**Comment by AbhineshJha** [comment]
sorry to say sir @Rakesh9100 .!!! The html consists of xml file and i have not that much knowldge of that.
i have tried by best for making it responsive, but it does not work..
That's all about this pr.
If you think this is a faulty pr without responsiveness, u can close the pr if not then.........

**Comment by AbhineshJha** [comment]
pls can u give me a  update regarding so i can work on another pr  ? @Rakesh9100

**Comment by Rakesh9100** [comment]
If you don't have knowledge of XML, then how you have added that and made this component?

Are you just copying the components from somewhere and including in this repository @AbhineshJha

**Comment by AbhineshJha** [comment]
Okeh ! that's the point !! 
So as you know this is an AI generation, nobody is gonna write code from scratch . 
i just explore contents over internet and then combines the components and make a program with the help of AI (not completely)
.
And deep down you also know that everyone is doin the same @Rakesh9100 
That's the reality

**Comment by Rakesh9100** [comment]
Yes, this is definitely true!! I just want to say that taking help and exploring is good and should be done but don't copy any content fully from somewhere and just paste here for the points.

I hope you are not doing the same!! @AbhineshJha

**Comment by AbhineshJha** [comment]
Sure !! i'll also take care of minor  thing form onwards .. @Rakesh9100

**Comment by Rakesh9100** [comment]
Can you modify this component code and use only HTML and no XML @AbhineshJha

**Comment by AbhineshJha** [comment]
Extremely sorry sir ! cuz the upper slider is created in xml , and i as you know html does not support features like this @Rakesh9100

**Comment by AbhineshJha** [comment]
I have tried xml file for the first time in html file , i think i have to firstly understand xml then have to implement .
i can see , how dominant has this become 😄

**Comment by Rakesh9100** [comment]
Right, and this is the only point I want to keep. You should first learn that language to a certain basic or intermediate level and then contribute or contribute in the languages you are comfortable with so that you can make any changes easily @AbhineshJha

**Comment by AbhineshJha** [comment]
Thanks for correcting me  @Rakesh9100 , i'll definately mind this form onwards ..!

**Comment by Rakesh9100** [comment]
Merged this time ✨ @AbhineshJha

**Comment by AbhineshJha** [comment]
thankyoouuuuuuu @Rakesh9100

**Pull request merged**
